### ISSUE TITLE
Unable to get reload now to work on local server

### ISSUE THREAD

**Issue by stevegdavis** [bfabiszewski/ulogger-server#100]
Hi, I have installed ulogger server (from latest zip file) on a Linux Mint machine. I can get most of the functions to work, (sync etc... from the android app) but not Reload now nor auto-reload nor last position. All works fine on your demo server. Here is a screen shot of the js that fails on click of Reload now button:-
![ulogger_reload_error](https://user-images.githubusercontent.com/15140454/66489072-ee00a080-eaa6-11e9-859c-188d314c89c9.JPG)

I have tried various browsers and deleted any cache on the browsers. Many Thanks.

**Comment by stevegdavis** [comment]
All works OK if I create another user but not with just 1 user ??

**Comment by bfabiszewski** [comment]
Thanks for the report, seems to be regression introduced by #79.
