### ISSUE TITLE
Default language for OSM rendering

### ISSUE THREAD

**Issue by plague-doctor** [bfabiszewski/ulogger-server#109]
Please add an option (env variable?) to setup a default language used for OSM rendering. 
It looks like the default language is a `local language` which renders the maps using Chinese (or Malaysian, Jewish, etc.) languages. It is nice to have a record of international trips, but I would like to be able to read the names of the cities in my own language.
Or maybe a list of languages could be used for multi-language users?

![map](https://user-images.githubusercontent.com/10541916/70283499-68367280-1815-11ea-8bda-533c88eb9a2c.png)

**Comment by bfabiszewski** [comment]
AFAIK it depends on map tiles you use. OpenStreetMap tiles are in local language. OpenCycleMap seems to give both local and English names. There are some sites that serve localized OpenStreetMap tiles, like https://www.osmap.info. 
If you find localized tiles that you want to use (and the host allows to use them), you may add this tile layer to µlogger through [config file](https://github.com/bfabiszewski/ulogger-server/blob/69cf9ade47a66fe5d6282ea643bf9c1262bbbbfc/config.default.php#L29).
