### ISSUE TITLE
Error uploading tracks with the app on Android

### ISSUE THREAD

**Issue by casbarro** [bfabiszewski/ulogger-server#110]
I installed ulogger on my webserver and everything works great (create tracks, edit tracks, etc.).
Now I installed the app (Android) and when I try to upload the track I get this error message: https://i.imgur.com/rbRkArP.jpg

Does someone know why?

**Comment by bfabiszewski** [comment]
Do you see any errors in system or web server logs?
What happens if you open client API page in web browser. Android client URL is your web server URL plus `client` subfolder, eg. `http://your_server.tld/client/index.php`

**Comment by bfabiszewski** [comment]
This is not expected result. See [demo server](http://ulogger-demo.herokuapp.com/client/index.php) message.

Which version of µlogger server and client do you use?

**Comment by casbarro** [comment]
I get the same message on the demo server:
![grafik](https://user-images.githubusercontent.com/230132/72908765-40a05880-3d36-11ea-9344-31fdf5c5241b.png)

On the webserver I use version μlogger 1.0-beta
On my Android device version 2.8

**Comment by bfabiszewski** [comment]
That's a bit different. On your server you get `"Unknown command"`. But that may be because you had logged in on your own server before the check. 
Which hosting provider do you use? I am asking because some providers block non-browser access by injecting javascript into each request.

**Comment by casbarro** [comment]
My provider is: https://www.df.eu/
I guess you will not know it.

Maybe I should try again installing the docker container on my Synology NAS, which I had other issues too.

**Comment by bfabiszewski** [comment]
I can't find any info about anti-bot features on this hosting.
Try to query your client page with `curl`, eg. `curl -v http://ulogger-demo.herokuapp.com/client/index.php`. If you don't have curl on command line, use some online service like https://reqbin.com/curl. You should get same response as from browser. Some hostings return a script which redirects to the real page. Such script works only in browser.

**Comment by casbarro** [comment]
By running a curl I get the following message:
`{
    "error": true,
    "message": "Unauthorized"
}`

It's pretty strange. Now I get this message in every browser, even if I just call the URL.
but I still get the error message in the app, even if I put the right login credentials and the url including index.php at the end. Do you have more advices for me?

**Comment by casbarro** [comment]
![Screenshot_20200123_001453_net fabiszewski ulogger-01](https://user-images.githubusercontent.com/230132/72943649-e96ea800-3d76-11ea-821d-45c99cbc767d.jpeg)

**Comment by bfabiszewski** [comment]
Curl result means that your hosting is ok. Now you get unauthorized, because previously you were logged in in your browser. That's ok.

But now your server URL in settings is wrong (screenshot). You should give main URL of your µlogger server without `client` part, eg. `http://your-domain.tld`.

If you correct that and it still does not work it means there is problem with your server setup. You should look into server logs for any warnings or errors.

**Comment by casbarro** [comment]
I now have installed a new uLogger instance (Docker container) on different Hardware, a Synology NAS. Even with that I can connect via Browser and can edit/view the tracks. But on the Android App I again get the same error, as shown in my first comment.

In the log files I can see this line:

```
172.17.0.1 - - [23/Jan/2020:23:06:22 +0000] "POST /client/index.php HTTP/1.1" 200 50 "-" "ulogger/2.8; Dalvik/2.1.0 (Linux; U; And
roid 10; LYA-L29 Build/HUAWEILYA-L29)" "-"  
```

The curl answer ist still:

`{
    "error": true,
    "message": "Unauthorized"
}`

Do you have any idea?

**Comment by bfabiszewski** [comment]
It seems that adding new track from client fails. You may try to add track from command line to make sure this is the problem and to see server answer.
Following two commands will add new track. Substitute `$USER`, `$PASS` and `$URL` with real values. It must be run from command line as it creates `cookies` file in current directory, which may be deleted after tests.
```
curl -c ./cookies -d "action=auth&user=$USER&pass=$PASS" -X POST http://$URL/client/index.php

curl -b ./cookies -d "action=addtrack&track=test_track" -X POST http://$URL/client/index.php
```

Correct answer is `{"error":false}` and `{"error":false,"trackid":123}` where `123` is new track id.

In case of server errors log messages are written to [system defined logger](https://github.com/bfabiszewski/ulogger-server/blob/149875af35422ebc938a5f4e8a57d9ad9dbbc0f9/helpers/track.php#L90). The exact log destination depends on your setup. Look for any errors in `/var/log/syslog`, `/var/log/messages` and PHP and web server logs.

Which database backend do you use?

**Comment by casbarro** [comment]
After running this command (replacing the variables):
`curl -c ./cookies -d "action=auth&user=$USER&pass=$PASS" -X POST http://$URL/client/index.php`
I get this anwer:
`{"error":false}`

Request:
`curl -b ./cookies -d "action=addtrack&track=test_track" -X POST http://$URL/client/index.php`
Answer:
`{"error":true,"message":"Unauthorized"}`

I'm currently running your docker container, but I don't know how to access the `/var/log` folders... I guess that my technical know how isn't enough to run such a service. You would probably just need 5 minutes to get it run. :D
Sorry for taking so much of your time. I think I will stick to the web service, without using the app...

**Comment by bfabiszewski** [comment]
The result you get is strange. First command should authorize you and store session id in cookie. The response you get from first command is correct. No error. But you are still unauthorized in second step. Something is going wrong here.
Really difficult to solve it. Unfortunately the application lacks proper error reporting.

In docker container logs are redirected to stdout and stderr. You should get it with `docker logs -f ulogger`.

**Comment by casbarro** [comment]
In the logs (stdout) I get these two entries, when I try to upload a track with the app:

`

2020-01-26 19:01:08 | stdout | 172.17.0.1 - - [26/Jan/2020:19:01:08 +0000] "POST /client/index.php HTTP/1.1" 200 50 "-" "ulogger/2.8; Dalvik/2.1.0 (Linux; U; Android 10; LYA-L29 Build/HUAWEILYA-L29)" "-"
-- | -- | --
2020-01-26 19:01:08 | stdout | 172.17.0.1 - - [26/Jan/2020:19:01:08 +0000] "POST /client/index.php HTTP/1.1" 200 25 "-" "ulogger/2.8; Dalvik/2.1.0 (Linux; U; Android 10; LYA-L29 Build/HUAWEILYA-L29)" "-"

`

**Comment by bfabiszewski** [comment]
Nothing wrong here. I have no idea. 
Maybe you experience some bug in Android 10? I tested the app on Android 10 in emulator though without any issues.

**Comment by casbarro** [comment]
I can't believe it! I found the problem.
At the beginning I created a new track, in the app. Just for testing. Afterwards I installed uLogger on both my Webservers and typed in the login credentials into the app.
The problem: I didn't created a new track, after typing the login credentials. I guess the app makes a request to the server, asking if the track is existing and the server answers with "no". So, instead of creating the new track, the app emits an error. I hope you understand my explanation.

Thank you very much for your great support and your time!! I will be very happy to use your great application.

**Comment by bfabiszewski** [comment]
Good to hear you solved it!
The scenario was probably more complicated than you describe it, because application would create new track if it didn't exist on server. Problem might be that you started the track on one server and later switch to another one where the track didn't exist, but application already received track id from server. Never mind!

**Comment by Ammiszaddaj** [comment]
Hello,
I had exactly the same error message in android app after reinstalling (updating) server. Problem was that i used the app before and there was old track. It was synced and tracking turned off before changing server. Solution was to click "new track" in app. Sincerely

**Comment by Evidlo** [comment]
> Problem might be that you started the track on one server and later switch to another one where the track didn't exist, but application already received track id from server.

I have this situation now.  Is there any simple fix for this or do I have to fiddle with the SQL database?

**Comment by bfabiszewski** [comment]
No simple solution.
When new track is synchronized with the client, the ID is created on server and saved on client.
If you change the server and try to upload recorded track to new server, the ID will probably not exist there or it may belong to another track.
You may try to manually create track on the new server. You will have to copy the ID from the old one.
Or just export the track to GPX file and import it from the file on the server.
