### ISSUE TITLE
js/dist/bundle.js is missing

### ISSUE THREAD

**Issue by jpfox** [bfabiszewski/ulogger-server#114]
Hi,

After upgrade to last version (today), ulogger/js/dist/bundle.js is missing

Have I to install npm and all necessary dev stuff to get it ?

Thanks for your help

**Comment by bfabiszewski** [comment]
You are fast!

I am preparing to release new version, but it is not production quality yet. 

You may test it but there are still things that need to be fixed and documented. For example there is small change in [database scheme](https://github.com/bfabiszewski/ulogger-server/commit/7e225866b10932a83021feca40f4147e0f69e044#diff-a0f67b6084a265e0871f50a5e26e9fba).

Generally from now on for the development version you will have to build javascript bundle yourself by installing npm and dependencies. Basic instructions are in [Readme](https://github.com/bfabiszewski/ulogger-server#install). 

Or you may wait for 1.0 release to be ready. I will upload it then with prebuilt javascript bundle.

**Comment by jpfox** [comment]
Oops, sorry, I had not seen that there were commits after 0.6 tag. I've just revert to 0.6 tag commit and all is fine now. Just had to convert mysql connection config (dsn mode).

Thanks for your quick answer.

My friends, family members and I are happy to use a "libre" solution to track our path without beeing tracked ;-)

**Comment by KoljaL** [comment]
Is there a way to get a pre-version of the bundle.js?
My ulogger runs on a webspace and i cant install npm.

By the Way: Thank you for this logger :-)

**Comment by bfabiszewski** [comment]
Maybe you could install it locally, generate bundle and upload to your server?

**Comment by KoljaL** [comment]
I could try, but i don`t have experience with it.

What is the reason for this way, to create this file after the installation?

**Comment by bfabiszewski** [comment]
The reason is the necessity of synchronization between distribution bundle and source code. I should probably create a hook on commit or push. As such the build process will slow down a bit each git operation. And usually users that want to use development branch are able to use required build tools. 
But you may be right that in our case, with infrequent releases, it would be better to provide the bundle.

**Comment by bfabiszewski** [comment]
I added js bundle to development branch.

**Comment by KoljaL** [comment]
Great, it works .-)
