### ISSUE TITLE
Error while migrating server

### ISSUE THREAD

**Issue by Jhyrachy** [bfabiszewski/ulogger-server#116]
Hi,  
I'm migrating server host but I want to keep all my users and tracks.  

I downloaded the _data folder in the attached volume of the docker container and I uploaded it in the volume of the new installation.  

I then changed ownership and group to systemd-network and systemd-timesync, as is was in the previous install.

But now, when I try to connect, I get this error:
`Database connection error (SQLSTATE[HY000] [2002] Connection refused)`

Any idea what could be the cause?

**Comment by bfabiszewski** [comment]
Hi,
Which version is it? Any of the releases or development git version?
Which database engine?

Are you migrating to the same version of µLogger?

**Comment by Jhyrachy** [comment]
Hi!  
It was my fault I was migrating to 0.5 to 0.6

I was sure I added :v0.5 at the end of the image, but I probably missed it.

Reinstalled from zero using:
`docker run --name ulogger -p 8080:80 -d bfabiszewski/ulogger:v0.5`

and it worked flawlessly

Sorry to had bothered you
