### ISSUE TITLE
Android 10 - allow always (gps permission) not possible with foreground app

### ISSUE THREAD

**Issue by MalakymR** [bfabiszewski/ulogger-server#118]
There is no "Allow always" for GPS permission for ulogger.

This is likely because of the "foreground" mitigations to get around Android killing "background" services in the past.

Some similar screenshots here https://wigle.net/phpbb/viewtopic.php?f=13&p=10401

**Comment by bfabiszewski** [comment]
Did you read the [answer](https://wigle.net/phpbb/viewtopic.php?f=13&p=10401#p10401) to the post you refer to? It also applies to our case. No need for "Allow always". We only need permission while using the app.

This issue belongs to [ulogger-android](https://github.com/bfabiszewski/ulogger-android) repo. 
If you still think this is an issue, please report there.
