### ISSUE TITLE
Impossible to modify initial longitude/latitude

### ISSUE THREAD

**Issue by Thieume** [bfabiszewski/ulogger-server#121]
Hello,
I'm running µlogger 1-0-beta (as writen on the bottom right of the screen) on a Synology NAS, on a "normal" environment (not a Docker one) with MySQL (MariaDB).
I cannot change the initial longitude and latitude in the settings. Nothing is never changed if I type the values or change them with the +/- arrows.
The only way is to modify the blob files in the database.

Regards,
Matthieu.

**Comment by bfabiszewski** [comment]
Thanks for the report!
