### ISSUE TITLE
update default password

### ISSUE THREAD

**Issue by Ajwani97** [bfabiszewski/ulogger-server#122]
Please note: I found this leak via a web scanner.
Is there an automated way to update the default password for admin? Or force update? As the credentials present in the sqlite file are leaked. There's a recommended way to set it up via env..

Thanks a lot for your time :)

**Comment by bfabiszewski** [comment]
Thanks for the report!

Could you explain a bit more? What leak do you mean?
There is no default admin password. When you install the application with setup script you choose you admin username and password.

**Comment by Ajwani97** [comment]
Leak in the sense: default creds are stored in scripts/ulogger.sqlite file. That's y I just wanted to confirm if there's an automated mechanism to change password upon installation..

**Comment by bfabiszewski** [comment]
If you mean [this line](https://github.com/bfabiszewski/ulogger-server/blob/6c032ddc5a155ceaeac307386ad02508efbcd151/scripts/ulogger.sqlite#L138) it is commented out. So it will never be executed in this script.

**Comment by Ajwani97** [comment]
Apologies for taking your time.. Thanks, I just blindly reported it out..

**Comment by bfabiszewski** [comment]
Not a problem. Thanks anyway for reporting!
