### ISSUE TITLE
Support for other map providers

### ISSUE THREAD

**Issue by mapl** [bfabiszewski/ulogger-server#124]
Just a lousy enhancement request to add support for other map provider besides OpenStreetMap and Google Maps, where the user can actually set its provider of choice.

**Comment by bfabiszewski** [comment]
What other providers do you mean? Can you give an example?

Currently there is support for two map engines: Google Maps and OpenLayers. 
For OpenLayers engine user may add compatible XYZ map layers in µLogger configuration. There are many compatible free or commercial map tiles providers, like OpenStreetMap, OpenCycleMap, MapBox, Stamen, HERE etc. Some examples are [listed here](https://wiki.openstreetmap.org/wiki/List_of_OSM-based_services).

**Comment by mapl** [comment]
Well, as vector tiles, in opposite to high traffic raster tiles, are becoming more and more common. MapBox GL is something worth to take look at.

**Comment by bfabiszewski** [comment]
If you mean adding support for vector tiles I think this should not be difficult as OpenLayers engine supports it. 
The main issue would be to redesign the way of storing and adding layers from UI because we would also have to store information about layer format. Unless we could detect format from tile URL…

**Comment by bfabiszewski** [comment]
I made some tests. As adding vector tiles is not difficult, they require enhanced GUI for user to be able to add layers and styles.
Also adding another engine is not an option now. It will not give much improvement, but will significantly increase maintenance tasks.
I am closing it now. Maybe get back to the idea in future.
