### ISSUE TITLE
Feature request: track overlay

### ISSUE THREAD

**Issue by loogaru** [bfabiszewski/ulogger-server#129]
It would be very cool if I could add some gpx track as an overlay for another one (or display two tracks at the same time). Usecase: share my position on marathon route for supporters. If there was an overlay of full route it would be easier for them to plan their movement and get ready for my approach. Thanks!

**Comment by loogaru** [comment]
By the way, It's seems not very difficult but useful in this context to show on map current location of device that is browsing map.

**Comment by bfabiszewski** [comment]
This could be useful but currently I don't see an easy way to implement it. 
Maybe some future version when I find more free time.

**Comment by loogaru** [comment]
maybe overlay route url could be added as OpenLayers layer? Sorry if this question is nonsense, just searching for variants.

**Comment by bfabiszewski** [comment]
Not a nonsense :) Could be added as a vector layer.
Still this will not be a top priority feature for me.
