### ISSUE TITLE
How to add another user

### ISSUE THREAD

**Issue by sprnza** [bfabiszewski/ulogger-server#13]
Hi there!
Thank you for the project!
One little question: how to add another user account? Do I need to add it manually to my DB?

**Comment by bfabiszewski** [comment]
Hi!
You have to login with admin account. 
You set [admin user in configuration file](https://github.com/bfabiszewski/ulogger-server/blob/master/config.default.php#L67), e.g. `$admin_user = "sprnza";`.

**Comment by sprnza** [comment]
Super! Thanks!
