### ISSUE TITLE
Feature request: toggle marker groups

### ISSUE THREAD

**Issue by loogaru** [bfabiszewski/ulogger-server#130]
Map looks a lot cleaner without unnecessary markers.
![marker_groups](https://user-images.githubusercontent.com/25899625/87095035-ac28a480-c248-11ea-9737-f6068b0411dd.png)
Also saving this settings to cookie file is very appreciated feature.

**Comment by bfabiszewski** [comment]
You are right. I have plans to do something with the markers.
