### ISSUE TITLE
Freehoster [No Issue]

### ISSUE THREAD

**Issue by mawoka-myblock** [bfabiszewski/ulogger-server#131]
Take a look at the german Hoster lima-city! I use it and it is good! (Good uptime and fast)

**Comment by bfabiszewski** [comment]
Thanks for the info!
If it allows to save uploaded files I could use it for my demo. Heroku does not allow permanent storage in free setup.
I'll give it a try

**Comment by bfabiszewski** [comment]
Hmm, I am unable to register on https://www.lima-city.de/register site. Whatever I put on Registrierung page it fails with no error message. Maybe it is a temporary problem. I'll try to come back later.

**Comment by jowagner66** [comment]
I used my lima-city.de (already existing) webspace to install an ulogger server this morning, works fine. If you continue having problems, I can double check.
