### ISSUE TITLE
ol_layers not saved, priority ignored

### ISSUE THREAD

**Issue by woffs** [bfabiszewski/ulogger-server#132]
Thank you for this great software.

After changing to the sqlite-based config in v1 always the layer with the largest id (Osmapa.pl) is the default. Selecting an other layer in the user web interface works. Saving another default via web preference interface does not work, the priority in the sqlite table is not changed. If I set the priority by hand in the sqlite table, it is displayed in the web preferences interface, but ignored for selecting the displayed layer.

System is Debian Stretch, php7.0. File tree is at git HEAD.

**Comment by bfabiszewski** [comment]
Thanks for reporting! 
I checked and there is an issue while storing layers with sqlite engine.

**Comment by woffs** [comment]
Now it works. Thank you a lot! :+1:

**Comment by bfabiszewski** [comment]
Thanks for feedback!
