### ISSUE TITLE
Maximum upload size not saved

### ISSUE THREAD

**Issue by Jhyrachy** [bfabiszewski/ulogger-server#133]
Hi, I'm trying to upload a file over the standard limit size (2Mb), so I tried to change it in the settings.  

Sadly it's not saved (others stuff, lik Minimum password lenght) is properly saved, and the upload it's prevented by the maximum size message error.

I'm using version 1.1-beta

**Comment by bfabiszewski** [comment]
When saving the application checks if the value is not greater than any system limits and adjusts the value in case system limit is lower.
Please check following PHP settings:
- upload_max_filesize
- post_max_size
- memory_limit

**Comment by Jhyrachy** [comment]
I'm sorry, but I can't find (I'm using the docker container) any php.ini or .htaccess to edit "upload_max_filesize" (I've seen that in utils.php you define the other 2 values in function of it)

**Comment by bfabiszewski** [comment]
You can create the files in they do not exist. Setting PHP variables depends on you particular setup.
For example in the docker file I use for testing it should be possible to set PHP variables in [nginx.conf](https://github.com/bfabiszewski/ulogger-server/blob/master/.docker/nginx.conf) file with `fastcgi_param  PHP_VALUE "upload_max_filesize = 10M"` 
If you use apache server you could add .htaccess file with relevant settings.
