### ISSUE TITLE
Node icons (white) missing when viewing track

### ISSUE THREAD

**Issue by stevegdavis** [bfabiszewski/ulogger-server#141]
I have just noticed that if I view http://ulogger-demo.herokuapp.com with Chrome or Edge (Windows 10 Pro) that only the start and end icons are visible but no other (white) nodes are visible sometimes there are black squares instead of the white icons. I can still click on the waymarks to get the popup. All icons appear OK on Firefox 81.0 see left hand side of screenshot (Android chrome browser is OK) as well). I tried all the usual clear cache etc...
![ulogger browser icon error](https://user-images.githubusercontent.com/15140454/94259997-53070d80-ff27-11ea-81e1-86738a919599.JPG)

**Comment by bfabiszewski** [comment]
Thanks for the report!
I am on mac now, but I gave it a quick test on browserstack.com (win 10, edge) and it looks correct there. 
I will try to do some more testing later on some windows machine.

![image](https://user-images.githubusercontent.com/3366666/94261530-4d62f500-ff32-11ea-8d3f-636635570643.png)

**Comment by stevegdavis** [comment]
Thanks for the reply. Not sure if this is any help but I just tried again and got the following on Chrome (Win 10).

![ulogger browser icon error 2](https://user-images.githubusercontent.com/15140454/94266794-83a07480-ff32-11ea-8b1a-c41a58acc23f.JPG)

However I have just tried on a Win 10 laptop and all is fine on Chrome and FF.

Also if I try to launch a debug session to Chrome from Visual Studio Code (server running on same Win 10 PC) I get an exception:-

![ulogger browser icon error VS Code Chrome](https://user-images.githubusercontent.com/15140454/94269318-6a99c280-ff36-11ea-932f-4f8878b9fc3c.JPG)

and launch VS code Firefox similar exception:-

![ulogger browser icon error VS Code Firefox](https://user-images.githubusercontent.com/15140454/94268898-c879da80-ff35-11ea-9a77-0a2b4da6f7a7.JPG)

I have always used VS Code in the past and had no problems with ulogger-server 0.6 on this machine.

**Comment by bfabiszewski** [comment]
This is a caught exception and it is normal. It doesn't affect the application.

Have a look at Chrome DevTools. There may be some hints in Console or Network tabs. In Network tab you may select "Disable cache" checkbox, reload page and look for problems.

**Comment by stevegdavis** [comment]
That's funny when I disable the exception breakpoints the chrome launch gets as far as the login page but then crashes (open browser closes) but carries on when launching to FF.
Console tab (Chrome) just says 'Navigated to http://ulogger-demo.herokuapp.com/'. Can't see anything untoward in any tab, screenshot of (Chrome) Network tab:-

![ulogger browser icon error 3](https://user-images.githubusercontent.com/15140454/94272577-24932d80-ff3b-11ea-9bb5-6911dab70750.JPG)

**Comment by bfabiszewski** [comment]
I checked on some windows 10 machines and I couldn't reproduce your problem. 
It seems to be limited to your particular setup.
Both Chrome and Edge are Chromium based, so it is possible that the engine is affected by some rare rendering problem related to your hardware/drivers. 
Anyway I don't think this is µlogger issue. You could try to report it upstream to openlayers or browsers teams.
Keep me updated if you find out anything.

**Comment by bfabiszewski** [comment]
You might try to turn off hardware acceleration in Chrome and see if that has any effect.

**Comment by stevegdavis** [comment]
Unable to solve the problem, tried other chromium based browsers they also show the same problem, however as you suggested turning off the hardware acceleration 'cures' the problem. However if I change the 'normal' iconStyle in api_openlayers.js file (and npm re-build) to say the stop icon the icons now appear OK:-

![ulogger browser stop icon](https://user-images.githubusercontent.com/15140454/94419582-e71ce300-017a-11eb-9db0-72f2c67d8a1c.JPG)

That in it's self is rather strange.

**Comment by stevegdavis** [comment]
Just found out it is an opacity problem on chrome, just removed the line opacity: 0.7, and the icons appear OK.

**Comment by bfabiszewski** [comment]
I just wanted to write it must be opacity issue. :)
You could prepare a simple test case and report it to openlayers.
Maybe it is fixable on their side?

**Comment by stevegdavis** [comment]
OK have you sent anything to the open layers team before, is there a forum or something?

**Comment by bfabiszewski** [comment]
I reported some issues at https://github.com/openlayers/openlayers/issues before.
They respond pretty fast.
It is better that you report this problem, because I can't even reproduce it.

**Comment by stevegdavis** [comment]
OK, thanks for your help, I will close this issue.

**Comment by bfabiszewski** [comment]
I found a fiddle that you could use as a base to create a test case:
https://jsfiddle.net/geocodezip/k5wzhvb3/5/
Originally it illustrated some other issue, but you could adjust it to show your problem.

**Comment by stevegdavis** [comment]
@bfabiszewski just a courtesy message to say the problem has now gone away on my Windows 10 PC, white markers appear OK, thanks again for your help.

**Comment by bfabiszewski** [comment]
Thanks for the update!
Out of curiosity, did you find out what the issue was?

**Comment by stevegdavis** [comment]
No, I didn't look into at all as per your suggestions , the only thing that has happened since is a usual Win10 update. I looked at updating the graphics driver but I couldn't it as the chipset on my PC is no longer supported, sorry can't explain it at all, probably it will return!!
