### ISSUE TITLE
Serving from reverse proxy at different path

### ISSUE THREAD

**Issue by MagicRB** [bfabiszewski/ulogger-server#145]
I need to have ulogger accessible at `https://example.com/ulogger`, that address is proxied to `http://someaddress.com/`. ulogger correctly detects that it's running behind a proxy, because it redirects to `https://example.com/`, but it's still missing the `/ulogger` part. Am I missing a header or something? or is it just that ulogger doesn't handle this case properly

**Comment by bfabiszewski** [comment]
How did you set up the proxy?
The problem is that µlogger detects base path from the server variables. The variables on the server where it is installed does not contain the `/ulogger` part. Maybe you could fix it by rewriting path when forwarding requests?

**Comment by Generator** [comment]
Also having issues with reverse proxy

```
	location ^~ /ulogger {
	    proxy_pass	http://ulogger/;
	    proxy_set_header Host $host;
	    proxy_set_header X-Real-IP $remote_addr;
	    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	    proxy_redirect          off;
	}
```

When try to open `domain.com/ulogger` redirects do `domain.com/uloggerlogin.php` (without '/').  
When open the current URL `domain.com/ulogger/login.php` after login redirects to `domain.com`
