### ISSUE TITLE
Upload tracks from mobile app leads to Bad URL error

### ISSUE THREAD

**Issue by derMitDemRadTanzt** [bfabiszewski/ulogger-server#147]
Hi, folks!

After the ulogger-server is up and running on my Debian 10 LAMP server in a local private network for testing purposes, I move forward a next step and test the track synchronization between mobile Android app and ulogger-server.

When I hit the upload button in the app, I receive Android toast messages about an error you see in the attached screenshot.

Does anyone has an idea what goes wrong?

The error messages include:

"Bad URL: no protocol: 192.168.1.181/client/index.php"

First toast: "Uploading started"

Second toast: "Uploading failed: Bad URL: no protocol: 192.168.1.181/client/index.php"

![Screenshot_20201022-113638](https://user-images.githubusercontent.com/47819327/96907175-e10fde80-1468-11eb-851f-806391284cfe.png)
![Screenshot_20201022-113641](https://user-images.githubusercontent.com/47819327/96907178-e1a87500-1468-11eb-92dd-de7434e39495.png)
![Screenshot_20201022-113645](https://user-images.githubusercontent.com/47819327/96907179-e1a87500-1468-11eb-9056-f4ecee6e3734.png)

Cheers!

**Comment by peteman52** [comment]
That are two problems:
1. No protocol means you have to start your URL with http(s)
2. An ip-address is no valid URL
So you can't do for example http://192.168.1.181 .

**Comment by derMitDemRadTanzt** [comment]
Yes, indeed. That was to obvious. Of course the protocol was missing. I am so accustomed to browser that "automagically" try to add default protocols to the domain name.

Using HTTP protocol and IP address http://192.168.1.181 works. As I am running the ulogger server in a local private network I do not possess a fully qualified domain name. Using the host name of the above IP address works as well. That would look this way: http://tpt60b. Thank you very much for expanding my horizon. Cheers!
