### ISSUE TITLE
Track color speed and altitude checkboxes not being re-enabled

### ISSUE THREAD

**Issue by stevegdavis** [bfabiszewski/ulogger-server#148]
I have just created a new track on the demo server called Auto_2020.11.02_16.46.54 with a few markers on it. I noticed that if I click (tick) latest position checkbox then the speed and altitude checkboxes are disabled as expected, however if I un-tick the latest position checkbox the speed and altitude checkboxes remain disabled, is this as expected ? thanks.

**Comment by bfabiszewski** [comment]
Thanks for the info. Seems to be a bug.

**Comment by stevegdavis** [comment]
@bfabiszewski Thanks for the reply. In the meantime is there a way for me to delete 2 auto track names from the demo server or can you do it for me:-
Auto_2020.11.03_08.58.40 and Auto_2020.11.02_16.46.54
thanks.

**Comment by bfabiszewski** [comment]
You can delete it logging in as demo user in edit track menu.
Anyway I have already done it for you.

**Comment by stevegdavis** [comment]
Many thanks, sorry I tried logging in as demo I must have mistyped the password!
