### ISSUE TITLE
started requiring login but login is turned off. 

### ISSUE THREAD

**Issue by katchy3132** [bfabiszewski/ulogger-server#150]
I thought I had things set up to have public tracks but it seems that it started requiring login:

from config table :

public_tracks | b:1;
 require_auth | b:0;

but in the gui, clicking on settings it has "require auth" checked and "public tracks" not checked. 

when I try to change it and click submit , it says "Something went wrong"

**Comment by bfabiszewski** [comment]
Maybe the table is corrupted? Did you modify it manually?
You may try to delete current row from config table. It should be recreated on first save. Of course you will loose all your settings and will have to set them up again in the gui.

**Comment by katchy3132** [comment]
I just nuked the entire DB and reran the setup. I was able to login but same thing - I tried changing settings and "Something went wrong "

**Comment by bfabiszewski** [comment]
Maybe some problem with database permissions?
Which version of the app? 
Which MySQL version, which PHP version?
Check webserver logs and system logs (syslog, messages) for any errors.

**Comment by katchy3132** [comment]
I was using the latest git repo. 
mysql 10.2.35-MariaDB
php 7.3.21 
that was on a shared hosting provider which is hard to debug.

I just tried again on another machine- using sqlite and got the same "something went wrong" 

in the logs I seethe following
```
FastCGI sent in stderr: "PHP message: PHP Notice:  
Undefined variable: lang in /home/ubuntu/ulogger/ulogger-server.git/utils/saveconfig.php on line 26
PHP message: PHP Notice:  
Trying to access array offset on value of type null in /home/ubuntu/ulogger/ulogger-server.git/utils/saveconfig.php on line 26" while reading response header from upstream
```

**Comment by bfabiszewski** [comment]
There seems to be a bug that prevents showing proper error message. But it means that somehow your user is not authorized to save config.

**Comment by katchy3132** [comment]
I am using the user I created during setup . And I see the settings , add user, and edit user in menu when logged in . in the database the user has a '1' for admin .

**Comment by bfabiszewski** [comment]
In the meantime I committed a fix to the problem visible in the log file. You may check if it changes anything.

**Comment by bfabiszewski** [comment]
Also look into system log files other that www/php logs.
Ulogger logs its internal errors using `syslog` with `LOG_ERR` priority. Depending on OS settings the log messages may land in different files, eg. syslog or messages.

**Comment by bfabiszewski** [comment]
Now that I think about your issues I realized that you may have problems with PHP sessions. Because it seems that main screen loads with proper permissions after authorization. But any subsequent calls to PHP are probably not authorized.
Make sure you have PHP session support installed, properly configured session permissions. And make sure you don't block cookies in your browser.

**Comment by katchy3132** [comment]
it must have been some combination of not saving cookies and the logfiles were configured incorrectly which was causing the process to fail. 

thank you! 

BTW in settings, the fields for latitude  and longitude only take values to 2 decimal places which isn't clear - it wasnt saving at all until i shortened the values.
