### ISSUE TITLE
离线地图

### ISSUE THREAD

**Issue by usersoul** [bfabiszewski/ulogger-server#152]
可以在服务器建立离线地图吗 直接调用服务器本地的离线地图加载显示而不是在线地图?

**Comment by bfabiszewski** [comment]
It should be possible to setup local map server and give its URL as tiles source. But I've never tried it.

**Comment by usersoul** [comment]
请问如何实现地图块的本地化呢?

**Comment by bfabiszewski** [comment]
You will have to search on Internet. Look for raster tiles servers. Ulogger needs XYZ tiles format. 
These may work, though never tried it:
https://www.maptiler.com/server/
https://ircama.github.io/osm-carto-tutorials/tile-server-ubuntu/
