### ISSUE TITLE
No input file specified.

### ISSUE THREAD

**Issue by githlp** [bfabiszewski/ulogger-server#153]
i followed the steps listed on https://github.com/bfabiszewski/ulogger-server but when i call

https://mydomain.de/ulogger-server/scripts/setup.php

the only thing i get is a page with "No input file specified."

What is missing here ?

**Comment by bfabiszewski** [comment]
Looks like a problem with PHP and web server setup.
Try to [google it](https://www.google.com/search?q=php+No+input+file+specified).
