### ISSUE TITLE
Feature Request - View All Users upon logon

### ISSUE THREAD

**Issue by pswilde** [bfabiszewski/ulogger-server#157]
Hello,
It would be nice to have a feature to enable viewing all user last location upon logon and/or by default. The option to view all users last location is already in the system, but it would be beneficial to have such a view when logging in.
I'm going to take a little look at the code myself and will submit code recommendations if I'm able to code it well enough :-)
Thanks,

**Comment by bfabiszewski** [comment]
This could be useful, but should be optional. I am personally not interested in all users last location. I usually log in only to see my latest track. Later on I may switch to all users to see if anyone else posted something in the meantime.

**Comment by pswilde** [comment]
Absolutely, optional for sure.
I think my intentions for the use of ulogger are likely different to the common use - I simply intend to use it so my wife and me can see where each other are (we've been using Google location sharing til now) so she'll want to log in and see me, and I her. Having the "All Users" screen is really useful, I'm just trying to prevent her a few clicks :laughing: .

**Comment by nexius76** [comment]
I think that could be useful also have a switch that permit simply only the update of last location instead of adding a point to an unwanted track. In such way I can definitively switch off google sharing location with my wife and sons. Would be really great!
