### ISSUE TITLE
Feature request - Update last location without logging track

### ISSUE THREAD

**Issue by nexius76** [bfabiszewski/ulogger-server#158]
I think that could be useful have a switch that permit simply only the update of last location instead of adding a point to an unwanted track. In such way ulogger can be used to definitively switch off google sharing location. Would be really great!

In the app should be present a button that simply start the update of device location according with app configiration settings, without start tracking.

Thanks a lot for your great job!

**Comment by bfabiszewski** [comment]
I don't plan to give up tracks with location points.
Tracks are main purpose of the application. Storing just one single location without any history would need different approach and would make the application more complicated. And I simply don't have time to do that.
Anyway you should still be able to use the application just for viewing single last location. The only problem would be still growing location history in a form of a track. As a workaround you could create new tracks periodically and delete old ones.
