### ISSUE TITLE
'This page didn't load Google Maps correctly' and not able to back to the OpenLayers

### ISSUE THREAD

**Issue by gjemiolo** [bfabiszewski/ulogger-server#16]
I would like to test if gmaps will work without any specific configuration, but I've received just below error:
"Oops! Something went wrong.
This page didn't load Google Maps correctly. See the JavaScript console for technical details."

Unfortunately, there is no way to get back to the OSM..
It seems like the app ignores my attempt (choice) and use setting stored in cookie..

**Comment by bfabiszewski** [comment]
It seems google maps api key is now required.
I added key, please try again.

**Comment by bfabiszewski** [comment]
My previous comment assumes you are using my demo.

If you are talking about your own installation you will probably have to add google maps key in config file.

Anyway I will have to fix it to give user possibility to go back to osm.

**Comment by gjemiolo** [comment]
Yes, it was regarding my own server.
Sorry that I didn't clarified that first.

**Comment by bfabiszewski** [comment]
I'll try to fix it.
In the meantime the only solution is probably to clear cookies in your browser.

**Comment by gjemiolo** [comment]
Thx!
