### ISSUE TITLE
Timestamps incorrect

### ISSUE THREAD

**Issue by gnusupport** [bfabiszewski/ulogger-server#160]
Hello,

I can see this error since quite some time. You can observe it below. Though the track names say they were made in 2021, the actual timestamp is in 2001. This has been obtained by downloading the GPX from the server. Now where is exactly the error, I do not know. Maybe the mobile application makes the error, maybe server, maybe download of GPX makes the error with timestamps.

```
<?xml version="1.0" encoding="UTF-8"?>
 <gpx xmlns="http://www.topografix.com/GPX/1/1" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://w
  <metadata>
   <name>Auto_2021.01.22_07.27.47</name>
   <time>2001-06-08T04:28:37Z</time>
  </metadata>
  <trk>
   <name>Auto_2021.01.22_07.27.47</name>
   <trkseg>
    <trkpt lat="2.59098908" lon="33.7561254">
     <ele>1130</ele>
     <time>2001-06-08T04:28:37Z</time>
     <name>1</name>
     <extensions>
```

**Comment by bfabiszewski** [comment]
Please export same track directly from mobile device and post here.

**Comment by gnusupport** [comment]
* Bartek Fabiszewski ***@***.***> [2021-03-13 14:56]:
> Please export same track directly from mobile device and post here.

I have tried it, now I see that time is correctly recorded. But this
is definitely not always. This is track that I did not yet finish.

Track directly from mobile device:
==================================

<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<gpx xmlns="http://www.topografix.com/GPX/1/1" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd https://github.com/bfabiszewski/ulogger-android/1 https://raw.githubusercontent.com/bfabiszewski/ulogger-server/master/scripts/gpx_extensions1.xsd" version="1.1" creator="μlogger 3.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ulogger="https://github.com/bfabiszewski/ulogger-android/1">
  <metadata>
    <name>Auto_2021.03.12_07.54.06</name>
    <time>2021-03-12T05:31:06Z</time>
  </metadata>
  <trk>
    <name>Auto_2021.03.12_07.54.06</name>
    <trkseg>
      <trkpt lat="0.35842264" lon="32.58482088">
        <ele>1203.0</ele>
        <time>2021-03-12T05:31:06Z</time>
        <name>1</name>
        <extensions>
          <ulogger:accuracy>77.0</ulogger:accuracy>
          <ulogger:provider>gps</ulogger:provider>
        </extensions>
      </trkpt>
      <trkpt lat="0.35957591" lon="32.58467637">
        <ele>1198.0</ele>
        <time>2021-03-13T08:26:43Z</time>
        <name>2</name>

Server export:
==============

<?xml version="1.0" encoding="UTF-8"?>
<gpx xmlns="http://www.topografix.com/GPX/1/1" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd https://github.com/bfabiszewski/ulogger-android/1 https://raw.githubusercontent.com/bfabiszewski/ulogger-server/master/scripts/gpx_extensions1.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ulogger="https://github.com/bfabiszewski/ulogger-android/1" creator="μlogger-server 1.0" version="1.1">
 <metadata>
  <name>Auto_2021.03.12_07.54.06</name>
  <time>2021-03-12T05:31:06Z</time>
 </metadata>
 <trk>
  <name>Auto_2021.03.12_07.54.06</name>
  <trkseg>
   <trkpt lat="0.35842264" lon="32.58482088">
    <ele>1203</ele>
    <time>2021-03-12T05:31:06Z</time>
    <name>1</name>
    <extensions>
     <ulogger:speed>0</ulogger:speed>
     <ulogger:bearing>0</ulogger:bearing>
     <ulogger:accuracy>77</ulogger:accuracy>
     <ulogger:provider>gps</ulogger:provider>
    </extensions>
   </trkpt>

Previous track that I finished recording has incorrect times:
=============================================================

<?xml version="1.0" encoding="UTF-8"?>
<gpx xmlns="http://www.topografix.com/GPX/1/1" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd https://github.com/bfabiszewski/ulogger-android/1 https://raw.githubusercontent.com/bfabiszewski/ulogger-server/master/scripts/gpx_extensions1.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ulogger="https://github.com/bfabiszewski/ulogger-android/1" creator="μlogger-server 1.0" version="1.1">
 <metadata>
  <name>Auto_2021.03.09_14.09.21</name>
  <time>2001-07-24T13:52:04Z</time>
 </metadata>
 <trk>
  <name>Auto_2021.03.09_14.09.21</name>
  <trkseg>
   <trkpt lat="0.05390641" lon="32.48142577">
    <ele>1124</ele>
    <time>2001-07-24T13:52:04Z</time>
    <name>1</name>
    <extensions>
     <ulogger:speed>0</ulogger:speed>
     <ulogger:bearing>0</ulogger:bearing>
     <ulogger:accuracy>55</ulogger:accuracy>
     <ulogger:provider>gps</ulogger:provider>
    </extensions>
   </trkpt>

Any other randomly exported track has incorrect times:
======================================================

<?xml version="1.0" encoding="UTF-8"?>
<gpx xmlns="http://www.topografix.com/GPX/1/1" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd https://github.com/bfabiszewski/ulogger-android/1 https://raw.githubusercontent.com/bfabiszewski/ulogger-server/master/scripts/gpx_extensions1.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ulogger="https://github.com/bfabiszewski/ulogger-android/1" creator="μlogger-server 1.0" version="1.1">
 <metadata>
  <name>Auto_2021.02.07_11.35.50</name>
  <time>2001-06-24T08:35:58Z</time>
 </metadata>
 <trk>
  <name>Auto_2021.02.07_11.35.50</name>
  <trkseg>
   <trkpt lat="-0.13328803" lon="30.49441926">
    <ele>1420</ele>
    <time>2001-06-24T08:35:58Z</time>
    <name>1</name>
    <extensions>
     <ulogger:speed>6.75</ulogger:speed>
     <ulogger:bearing>248.80000305176</ulogger:bearing>
     <ulogger:accuracy>14</ulogger:accuracy>
     <ulogger:provider>gps</ulogger:provider>
    </extensions>
   </trkpt>
   <trkpt lat="-0.13420238" lon="30.4921978">
    <ele>1416</ele>
    <time>2001-06-24T08:36:59Z</time>
    <name>2</name>
    <extensions>
     <ulogger:speed>0</ulogger:speed>
     <ulogger:bearing>0</ulogger:bearing>
     <ulogger:accuracy>18</ulogger:accuracy>
     <ulogger:provider>gps</ulogger:provider>
    </extensions>
   </trkpt>
   <trkpt lat="-0.13713329" lon="30.49005849">
    <ele>1424</ele>
    <time>2001-06-24T08:38:58Z</time>
    <name>3</name>
    <extensions>

I cannot find a track that I export that has not get 2001 in the
name. Only latest one had the right times.

**Comment by bfabiszewski** [comment]
We still don't know if it happens on the client or on the server.
Next time you encounter incorrect timestamps on server check the timestamps in client export.

This could be old GPS chipset [rollover bug](https://en.wikipedia.org/wiki/GPS_Week_Number_Rollover). 
Generally it shouldn't happen as [I fixed it](https://github.com/bfabiszewski/ulogger-android/commit/b4ce16100273d574f0997956f7b689c64d3c3484). Maybe the fix does not work in all cases?
Was your last test track (with good timestamps) recorded on the same device as previous ones?

**Comment by gnusupport** [comment]
* Bartek Fabiszewski ***@***.***> [2021-03-14 20:26]:
> We still don't know if it happens on the client or on the server.
> Next time you encounter incorrect timestamps on server check the timestamps in client export.
> 
> This could be old GPS chipset [rollover bug](https://en.wikipedia.org/wiki/GPS_Week_Number_Rollover). 
> Generally it shouldn't happen as [I fixed it](https://github.com/bfabiszewski/ulogger-android/commit/b4ce16100273d574f0997956f7b689c64d3c3484). Maybe the fix does not work in all cases?
> Was your last test track (with good timestamps) recorded on the same device as previous ones?

Last test track was recorded from same device, but now I am uploading
from other devices, I used Motorola E and E LTE mobile phones. What I
think is that I maybe did not update the software from F-Droid, and
that after update it started working well.

Do you know formula to use to add time to incorrect times? Should I
just add 20 years? I will experiment with it.

Please keep this issue open until I confirm that in new versions of
µlogger I do not get this problem.

**Comment by bfabiszewski** [comment]
You must add exactly 1024 weeks.
The problem was most probably not updated version of µlogger.

**Comment by gnusupport** [comment]
* Bartek Fabiszewski ***@***.***> [2021-03-23 13:09]:
> You must add exactly 1024 weeks.
> The problem was most probably not updated version of µlogger.

I have made some Emacs Lisp functions to add 1024 weeks, and to
replace the line with it.  Then it can be automated by using macro F4,
F4, and there could be different other ways to replace it with `sed`
for example or other tools.

You may close this issue as now I do not see problem taking place any more.

(defun rcd-sql-time-add-1024-weeks (timestamp)
  (let ((sql (format "SELECT '%s'::timestamp + interval '1024 weeks'" timestamp)))
    (rcd-sql-first sql *cf*)))

(defun rcd-gpx-replace-time ()
  (interactive)
  (let* ((line (thing-at-point 'line t))
	 (match (string-match "<time>" line)))
    (when match
      (let* ((start (+ 6 (string-match "<time>" line)))
	     (end (string-match "</time>" line)))
	(when (and start end)
	  (let* ((timestamp (substring line start end))
		 (new-time (rcd-sql-time-add-1024-weeks timestamp))
		 (first-part (substring line 0 start))
		 (last-part (substring line end (length line)))
		 (new-string (string-trim (concat first-part new-time last-part))))
	    (beginning-of-line)
	    (kill-line)
	    (insert new-string)))))))
