### ISSUE TITLE
Zoom resets on autoreload

### ISSUE THREAD

**Issue by sinus-x** [bfabiszewski/ulogger-server#161]
When the "autoreload" and "latest position" options are enabled and new positions are being sent from mobile device, the zoom resets back to default with every update. Would it be possible to keep it as it is? This way it's neccesary to adjust it every time it updates.

**Comment by martin-tef** [comment]
How about implementing a "follow" feature like in flighradar24? The map will always be centered on the last position and the manually adjusted zoom level will be respected for the next reload. This could either result in an additional checkbox or one of the existing functions will be modified to this behaviour.

**Comment by bfabiszewski** [comment]
I need to change the way autoreload works.
I've been busy lately. I hope to find some time to do it soon.

**Comment by sinus-x** [comment]
Bumping, I still think the server would benefit from having this.

**Comment by MalakymR** [comment]
I'd like to bump this again, almost makes it unusable.

As a stop gap - the default level is way too far zoomed in. It's also too far for ESRI imaging.

**Comment by MalakymR** [comment]
Was this supposed to fix the issue whilst using _autoreload_ and _latest position_ at the same time? As it still does this in v1.2.
