### ISSUE TITLE
[ERROR] InnoDB: preallocating 12582912 bytes for file ./ibtmp1 failed with error 95

### ISSUE THREAD

**Issue by nukedupe** [bfabiszewski/ulogger-server#162]
Hi,
i have got some mysqld problems. Updating alpine to 3.13 and error is gone.

**Comment by bfabiszewski** [comment]
This must be somehow related to your host setup.

Look at your PR.
On test system current configuration works fine but alpine 3.13 causes mysql problems:
https://travis-ci.com/github/bfabiszewski/ulogger-server/jobs/498982928

Could you check that?

**Comment by nukedupe** [comment]
Got it. They changed default configuration for mysql. Default is now skip network.
Perhaps you now know the best place to run this command. Maybe directly in the Dockerfile or in another script?
```
sed -i "s|.*skip-networking.*|#skip-networking|g" /etc/my.cnf.d/mariadb-server.cnf
```

**Comment by bfabiszewski** [comment]
Thanks for checking it!
Could you add the line in your PR?
I suppose anywhere in the [else block in the `init.sh`](https://github.com/bfabiszewski/ulogger-server/blob/eca74149a3aebd91ec7953778129dcebc43083cc/.docker/init.sh#L54) file would be fine.

**Comment by nukedupe** [comment]
Thanks for help.
Is added to PR.
Now all passed :)

**Comment by bfabiszewski** [comment]
Great! Thanks for this contribution.
