### ISSUE TITLE
Question:How to switch "markers" layer invisible in config

### ISSUE THREAD

**Issue by martin-tef** [bfabiszewski/ulogger-server#168]
When watching a long track with many points and low zoom level (e.g. 100km cycling track), having the markers layer visible does not make much sense. I would like to have the marker layer switched to invisible by default on my instance. Where can I do this in the config?

**Comment by martin-tef** [comment]
Found the answer myself. For those who are interested:

- open to ulogger-server/js/src/mapapi/api_openlayers.js
- under the line "this.map.addLayer(this.layerMarkers);" add two new lines:
    this.selectedLayer = this.layerMarkers;
    this.selectedLayer.setVisible(false);
- rebuild the js files in js/dist by running "npm run build" in js/src

**Comment by bfabiszewski** [comment]
I see you found some workaround.
I definitely have to add more flexibility to track viewing.
I just need to find some time to work on it.
