### ISSUE TITLE
Can't synchronize

### ISSUE THREAD

**Issue by aoguerrero** [bfabiszewski/ulogger-server#17]
Hi, I installed the ulogger client version 1.4 and the server side using the code on master, also I created a new user successfully, however, when I try to synchronize the following message appears:

`"Value <html><body><script of type java.lang.String cannot be converted to JSONObject"`

I installed the backend on the root path of the server, and used that address in the client configuration.

Thanks

**Comment by bfabiszewski** [comment]
It seems that the client tries to post to wrong address.

Client builds its target address by appending script name: `/client/index.php` to the base url that you enter in the host form, eg. `http://www.example.com`. The resulting address would be `http://www.example.com/client/index.php`.

Make sure you entered base url of your website, as above.

**Comment by aoguerrero** [comment]
Hi! the base url entered in "Server URL" is similar to http://ulogger.something.com
I tried:
http://ulogger.something.com/client/index.php
in the desktop browser and the response was:

{"error":false}

**Comment by bfabiszewski** [comment]
The response you get from desktop browser is expected. Do you get the same response from Android browser? 
Maybe the connection from the device is redirected? If you have access to your web server logs, check whether μlogger requests reach the server and where they land. Also check the request status code in the logs. 
If possible post the logs here (you may want to mask some sensitive data).

**Comment by bfabiszewski** [comment]
It is also possible that you provider uses some anti-bot feature and the request is redirected to a page that tries to set a cookie using javascript. You can trace such behaviour with `curl` or other similar tool.

**Comment by aoguerrero** [comment]
Hi! you're right, using a http client, I got his response:

```
<html>
    <body>
        <script type="text/javascript" src="/aes.js" ></script>
        <script>function toNumbers(d){var e=[];d.replace(/(..)/g,function(d){e.push(parseInt(d,16))});return e}function toHex(){for(var d=[],d=1==arguments.length&&arguments[0].constructor==Array?arguments[0]:arguments,e="",f=0;f
            <d.length;f++)e+=(16>d[f]?"0":"")+d[f].toString(16);return e.toLowerCase()}var a=toNumbers("f655ba9d09a112d4968c63579db590b4"),b=toNumbers("98344c2eee86c3994890592585b49f80"),c=toNumbers("82fc0c892184bce18a77abed92ebb53e");document.cookie="__test="+toHex(slowAES.decrypt(c,2,a,b))+"; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/"; location.href="http://ulogger.epizy.com/client/index.php?i=1";
            </script>
            <noscript>This site requires Javascript to work, please enable Javascript in your browser or use a browser with Javascript support</noscript>
        </body>
    </html>
```
It's a problem with the hosting provider, I'll switch to a home server, thanks for your help
