### ISSUE TITLE
docker method documentation improvements

### ISSUE THREAD

**Issue by khimaros** [bfabiszewski/ulogger-server#175]
a few issues encountered with the docker documentation:

- most users will want a volume mounted at /data so the data is not lost
- permissions required on /data must be 1000:50 (nobody:nobody)
- you must create a volume for /var/www/html/uploads/ with same perms
- if using sqlite, you must manually create /data/sqlite/ with same perms
- and then visit the "/scripts/setup.php" with your web browser
- with an old track with 350+ points, the app crashed when enabling synchronization

**Comment by bfabiszewski** [comment]
As mentioned in Readme docker is not production ready. I created it mainly for development purposes. Would be nice to create separate repo for the production docker with all the instructions, but I have not found time for that yet.
Regarding crashing you may want to open an issue in [ulogger-android ](https://github.com/bfabiszewski/ulogger-android) repo. As you mention large track the problem might just be a lack of resources on your device.
