### ISSUE TITLE
Compatible with OsmAnd Live Tracker?

### ISSUE THREAD

**Issue by LeOSW42** [bfabiszewski/ulogger-server#176]
Hello,

I have both ulogger and OSMAnd installed on my smartphone.
OSMAnd provides a live tracker feature that sends periodically a request to an URL with GET parameters (lat, lon, timestamp, hdop, altitude, speed).
I were not able to find the API documentation, but maybe this kind of feature is implemented?

Léo

**Comment by bfabiszewski** [comment]
Hi, µlogger is not compatible with OsmAnd and requires its own server in order to upload tracks.
