### ISSUE TITLE
Calendarview / Selecting a track per js

### ISSUE THREAD

**Issue by ahormann** [bfabiszewski/ulogger-server#177]
First of all thank you for the awesome project!

The only thing that I am missing is a calendar-view to pick a track by date. I think that would be less cluttered when many tracks are in the database.
I already tried to add this feature myself.
Because i could not get the (jQuery-) Calendar-picker to work under NodeJS I decided to use plain JS to select a new track via
`document.getElementById('track').value = newtrackId;` 
But after hours of debugging to get everything else to work i discovered that this does not trigger the onTrackSelect-function.
Since I have no experience with data-binding and NodeJS in general i hope that you can give me a hint how to solve this issue (trigger the onTrackSelect-function via js to read the new value).

**Comment by bfabiszewski** [comment]
Hi!
There is event listener set up for `change` event on this element. 
You can trigger the event by calling `dispatchEvent` on this element. [Read here](https://stackoverflow.com/a/2856602).
Better way would be to bind your element to view model. Observe change in view model and set `currentTrackId` directly.

**Comment by ahormann** [comment]
Awesome, thank you!
I am unfortunately not able to test this right now, but i think this should solve it. 
I'll tell you when i tested it.

**Comment by ahormann** [comment]
Just wanted to confirm that you solved my problem, thank you so much!
