### ISSUE TITLE
ulogger android app can not set waypoints

### ISSUE THREAD

**Issue by ventrig** [bfabiszewski/ulogger-server#186]
When trying to add a way point from the android app, the app quits without an error.  Ive tried reinstalling it and it still does the same thing.  I have the server up and running and it everything else works just fine.  Any help would be appreciated.

**Comment by bfabiszewski** [comment]
As this issue refers to Android app, I am going to close it here.
Please create new issue at https://github.com/bfabiszewski/ulogger-android.
In the new report please give more details: app version, Android version, device model.
