### ISSUE TITLE
iOS Tracker Client?

### ISSUE THREAD

**Issue by restah** [bfabiszewski/ulogger-server#188]
What a Great project, thanks for that!!!!

Is there a known iOS Client?

**Comment by bfabiszewski** [comment]
Thanks!
No iOS client that I know of. 
iOS is not free open-source projects friendly.

**Comment by restah** [comment]
Puh… damn… is the use via Get or Post Parameter posibel? If yes, can you List the Parameters?

**Comment by bfabiszewski** [comment]
It expects POST data.
For parameters please refer to actions in https://github.com/bfabiszewski/ulogger-server/blob/master/client/index.php#L58

**Comment by restah** [comment]
@bfabiszewski  Thanks !

I wrote a wrapper from iOS Traccar Client to µLogger [https://gist.github.com/restah/e04aac14a9fff4d5740b7b7079f48098](url)

The Field "Devicename" on the Client need the Track ID of µlogger.
