### ISSUE TITLE
change the suggested parameter for sqlite as it can lead people to use a temporary file as a database

### ISSUE THREAD

**Issue by martin-leo** [bfabiszewski/ulogger-server#192]
Hello,

I have started to use ulogger server a few days ago. I and stumbled upon a problem mainly caused by a lack of knowledge from myself, and a bit by the software itself, or rather by the comments in config.default.php. I think a modification could help to avoid that.

## the problem

So what happened (multiple times) :

1. uploaded the software on my server
2. modified the setup to use sqlite
3. used the suggested parameter "sqlite:/tmp/ulogger.db"
4. setup, login, everything is fine
5. a bit later : cannot login anymore

I think I understand now that /tmp is a temporary file and that explain why I cannot login after a while : the temporary file is gone.

## a solution

The "sqlite:/tmp/ulogger.db" suggestion may be changed to something else like "sqlite:/path/to/database.sqlite". So slow-minded people like me will not be tricked to use a temporary file that will be discarded later without them knowing.

Best regards,

leo

**Comment by bfabiszewski** [comment]
Thanks for letting me know!
I will change the examples as you suggests.
