### ISSUE TITLE
Can't setup ulogger server

### ISSUE THREAD

**Issue by ThoMagnum** [bfabiszewski/ulogger-server#196]
Hello,

most probably this is not an issue, more a user error, so sorry for that.
I want to setup ulogger on my synology to do some tests. For this spllite is totaly fine.

I editet "config.php" like attached, but I get alwas the following error:
####################################################
Database connection failed.

Please check database settings in 'config.php' file.

Server said: SQLSTATE[HY000] [14] unable to open database file

Please restart this script when you are done.
####################################################

Whatever I do, I get this error. First I tried without any credential information.

My goal is to create the sqllite DB in subfolder "db".

I appreciate your help.

Best regards, Thomas

[config.php.txt](https://github.com/bfabiszewski/ulogger-server/files/9008755/config.php.txt)
.

**Comment by ThoMagnum** [comment]
m

**Comment by bfabiszewski** [comment]
Hi, this may be permissions problem. Please make sure "db" folder is writable by web server.
Also please note that in your config the folder name is ".db", not "db".

**Comment by ThoMagnum** [comment]
Hi Bartek,
thanks for your quick help. Now it's running as expected.

Best regards, Thomas
