### ISSUE TITLE
Feature Request: Larger File Support

### ISSUE THREAD

**Issue by brimwats** [bfabiszewski/ulogger-server#199]
Hello!

I'd like to import my google maps data, but the gpx files resulting from the KML exports are much, much larger than 5242880 bytes. I can't find a way to increase this amount. Is there any way a higher amount could be allowed?

**Comment by bfabiszewski** [comment]
Did you try to change maximum uploaded file size in settings?

**Comment by brimwats** [comment]
I do not see a button for settings, and I didn't find a link to documentation of/for settings in the readme. Any pointers?

**Comment by bfabiszewski** [comment]
Menu at the bottom. You must be admin to see it.

![image](https://user-images.githubusercontent.com/3366666/184965340-51601503-5675-4f11-b09a-b5cbf1bfab85.png)

**Comment by brimwats** [comment]
> Menu at the bottom. You must be admin to see it.
> 


Well, that would explain that! Looks like a YUNOHOST config issue. I made https://github.com/YunoHost-Apps/ulogger_ynh/issues/21 to take care of it. thanks!
