### ISSUE TITLE
multiple user not possible

### ISSUE THREAD

**Issue by r100gs** [bfabiszewski/ulogger-server#20]
Hello,

thx for the very nice project!

for me its not possible to set multiple users.
If i create a new user the old user is not able to logon anymore
µlogger server 0.3 beta
µlogger app 1.5

Best regards,
Stefan

**Comment by bfabiszewski** [comment]
You should be able to add users when logged in with your admin account. 

Make sure you have set up your current user as an [admin in config file](https://github.com/bfabiszewski/ulogger-server/blob/master/config.default.php#L67).

**Comment by r100gs** [comment]
ok. 
my fault. Its working perfect now

Thank you
