### ISSUE TITLE
Bug: Admin settings does not save max upload size.

### ISSUE THREAD

**Issue by brimwats** [bfabiszewski/ulogger-server#200]
I finally sorted admin access.

I went into settings 
![image](https://user-images.githubusercontent.com/73113656/185571784-43766d39-dd90-4b2a-b9c1-2b422968e837.png)

then I set max size to 150

![image](https://user-images.githubusercontent.com/73113656/185571818-019a3b00-b6af-4e3a-bea7-a8c2a6018c5f.png)

but then when I try to upload something It only allows 2mb:

![image](https://user-images.githubusercontent.com/73113656/185571917-1c2225c4-3468-45ad-8594-105d0ff422cf.png)

if I refresh the page it resets to 2mb. What did I break?

**Comment by bfabiszewski** [comment]
This is probably limitation of your PHP settings.  It resets back to maximum value allowed by your system.
Check your PHP file size limits, especially `upload_max_filesize`, `post_max_size`, `memory_limit`

**Comment by bfabiszewski** [comment]
Also make sure your web server allows large uploads.

**Comment by brimwats** [comment]
> Also make sure your web server allows large uploads.

thanks for the tip! I updated the ulogger.conf and the php.ini (upped everything to 300MB)

I now got the 150mb thing to work in settings (it defaults to that). I go to upload a 130MB file, but:
![image](https://user-images.githubusercontent.com/73113656/185582445-8becfb00-c927-465c-80f1-3d796ee23482.png)
157286400 = 157mbm right?

**Comment by bfabiszewski** [comment]
Maybe the uploaded file is larger? What is the size reported by `ls -la` command?

Did you try to increase the limit, for example to 200, and see what happens?

**Comment by bfabiszewski** [comment]
There is also overhead resulting from the form encoding with POST method. 
Generally you should set the limit to a higher value than the file size itself.

**Comment by brimwats** [comment]
The actual file is on windows, so uploading via the browser. It is reported 

```
2022-05-07  12:52 PM            22,594 location_history_json_converter.py
2022-05-07  01:05 PM        40,891,581 Records.csv
2022-05-07  01:07 PM       129,688,951 Records.gpx
2022-05-07  01:09 PM       149,491,555 Records.gpxtracks
2022-05-07  11:22 AM       684,792,093 Records.json
2022-05-07  01:04 PM       263,230,043 Records.kml
```

So I upped it to 300mb:
![image](https://user-images.githubusercontent.com/73113656/185613006-84fb8d40-e793-4ed5-95e0-887806c11236.png)

after I did that I realized that I may have been trying to upload a 323mb file. So I retried the 120mb one. It seems like ulogger took it, but after a bit of time waiting, nothing seems to have happened... netdata doesn't report the server as under heavy load so I'll look into it a bit more.

**Comment by brimwats** [comment]
Some progress! I finally got a loading icon (three purple dots) ; but ended up with a 504 error. So I need to look into that one now :)

**Comment by bfabiszewski** [comment]
Look into system logs: web server, php, syslog for warnings or errors.

BTW µlogger was created to record and view short sport activities, like trekking, biking routes, usually divided into one day paths. It may not be suitable for such large data sets that you try to upload. Even if you manage to upload it the browser may have problems rendering it properly if there are too many waypoints in a single track.

**Comment by brimwats** [comment]
That's all very fair. I'll try the logs. I suspect it's just timeout on one of the php or scripts. the server has quite a few CPUs and 60+gb ram. I'm basically looking to transfer ~10yr of google location history somewhere so I can delete it from google. If you had other recs I should try I'd appreciate it!

**Comment by bfabiszewski** [comment]
You may try to change time limit in PHP: `max_execution_time`.
It may be also necessary to increase relevant timeout in web server settings.

Ten years of location history is too much. 
There are two options that come to my mind but may require some programming skills:
1. Write a script (or find one) to divide large gpx file into multiple one-day tracks. Now I realized there is [a script ](https://github.com/bfabiszewski/ulogger-server/blob/master/scripts/import_cli.php)bundled with µlogger that allows one to import multiple files from command line. I never used it, as it was contributed by another user. You could use it to import your divided paths. Maybe there is a tool that will let you export from google maps into single day paths?
2. Import the big file into µlogger. Use command line script if anything else fails. Write a script that will divide data imported into database into one-day paths.

**Comment by brimwats** [comment]
Thanks a ton for your support and insight! I'll close this as it is an issue on my end and not yours. I really appreciate it!
