### ISSUE TITLE
Lastest position button

### ISSUE THREAD

**Issue by alex000090** [bfabiszewski/ulogger-server#214]
Dear developers,
There in an issue with the "Latest position" button in web interface of the server. I have some different devices which I want to see on the map. To protect the server I made single user without admin privileges and some traks for each device. When I press "Latest position" button the interface switch track name (device in my case) to the track having really latest position independently of the previously selected track name.

**Comment by bfabiszewski** [comment]
It is not an error. The button shows the latest position of currently selected user.
It would be better to have each of your devices registered as a separate user.
The application will not work reliably when single user will be simultaneously in different places.

**Comment by alex000090** [comment]
Thank you for your answer! I'll use different users in this case.
