### ISSUE TITLE
Warnings when web server uses PHP 8.2.8

### ISSUE THREAD

**Issue by TheLancashireman** [bfabiszewski/ulogger-server#218]
Many thanks for providing this server!

PHP 8.2.8 gives warnings that  ${var} is deprecated and should be replaced with {$var}.

I found three instances. Here's a patch file that should adapt the affected files.

[php8.2.patch.txt](https://github.com/bfabiszewski/ulogger-server/files/12176926/php8.2.patch.txt)

**Comment by bfabiszewski** [comment]
Thanks a lot! I haven't tested with 8.2 yet.

**Comment by TheLancashireman** [comment]
> Thanks a lot! I haven't tested with 8.2 yet.

It seems to work well - I haven't encountered any problems yet. Just the warnings.
