### ISSUE TITLE
setup.php not working

### ISSUE THREAD

**Issue by Psynewaves** [bfabiszewski/ulogger-server#236]
Not sure what is going wrong here. I've loaded the program with docker and I can access the webgui, but the instructions said to load this file into the browser and follow the instructions, however there seems to be an issue as I have changed the file to $enabled = true;
But when loading the file into the browser, it reports that the file has not been edited.

![ulogger 1](https://github.com/user-attachments/assets/807145cb-e697-4e69-abcf-91a28f308f33)
![ulogger 2](https://github.com/user-attachments/assets/993a3720-0490-4625-a671-77733007166f)

**Comment by bfabiszewski** [comment]
This must be some docker issue. The file that is effectively served to the browser is probably still not edited.
Dockerfile has ENV parameter ULOGGER_ENABLE_SETUP. Set it to 1 when running you docker.
Something like this:
`docker run  -e ULOGGER_ENABLE_SETUP=1`
Anyway I only use this docker for testing. It may be not fully functional.

**Comment by Psynewaves** [comment]
Ah, right. I see. 
Thank you very much for your reply mate. I will have a go at that when I return home at the end of the week.
