### ISSUE TITLE
Synchronization fails

### ISSUE THREAD

**Issue by planetar** [bfabiszewski/ulogger-server#24]
I installed ulogger 1.3 on my Android phone and ulogger 0.3 beta on my debian jessie apache2 server.
Both sides seem to run s expected on their own but Synchronization gives this error:

"Value 0 of type Java.lang.Integer cannot be converted to JSONObject."

navigating to http://myServer.tld/client/index.php results in a 0 as return.

reading the servers log no obvious error occurrs, each sync attempt results in a line like:

2001:db8::0:c2ee:fbff:fe43:a8ed - - [20/Jun/2017:13:43:04 +0200] "POST /client/index.php HTTP/1.1" 200 272 "-" "ulogger; Dalvik/2.1.0 (Linux; U; Android 7.1.2; A0001 Build/NJH47B)"

or

10.187.122.97 - - [20/Jun/2017:13:46:08 +0200] "POST /client/index.php HTTP/1.1" 200 272 "-" "ulogger; Dalvik/2.1.0 (Linux; U; Android 7.1.2; A0001 Build/NJH47B)"

Searching for the error messages finds me a stackoverflow entry with this explanation:

"0 is not a valid json. Server should return something like {"response": 0} for this case"

What may be the issue here?

**Comment by bfabiszewski** [comment]
Strange, I don't know how it could output "0".
You can try to disable (comment out) **three lines** starting with [line 21 in auth.php](https://github.com/bfabiszewski/ulogger-server/blob/master/auth.php#L21).

Maybe it will give some more output when viewed from browser.

**Comment by planetar** [comment]
it is not just with sync, I get a "surplus 0" on about each call (visible in the top left corner of the page after login, both ff and chromium.
/utils/export.php?type=kml&userid=1&trackid=1 returns a blank page with a 0,
however, a tiny hello-world.php gives me "Hello world!" (and no 0)
this is with mod_fcgid

I did the out-commenting and found entries in the error log pointing to mod_fcgid: read data timeout, I changed the config of latter and those errors did not come again, but the problems persist.

most buttons on the server page (add user, import track, edit track) seem to run and actually do something, but still end with a message of "Something went wrong"

**Comment by bfabiszewski** [comment]
Please double check that you don't have any typos in config file.

Other that that I have no idea. You may try to trace it down commenting out parts of code or inserting some debug output. Then you may be able to see which line of code is printing "0".

**Comment by planetar** [comment]
ok, thanks, looks like you hit it.
There was in fact a 0 preceding the <php ...  and removing this fixed my issue.

My bad, thousand thanks for acting so very fast!
