### ISSUE TITLE
Install script can't setup database

### ISSUE THREAD

**Issue by stemy2** [bfabiszewski/ulogger-server#242]
Hello,

I have a problem for the database configuration. I'm using mysql so i tried some combinations that seemed to be logical (including the first choice mentioned in the comments above the said parameter, but the install script keeps saying the same error message:

`PDO::__construct(): Argument #1 ($dsn) must be a valid data source name`

So i'm a little stuck.

**Comment by virtadpt** [comment]
https://xkcd.com/979/
