### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by github-k8n** [bfabiszewski/ulogger-server#25]
It would be nice to have PostgreSQL (or sqlite) support for this.

**Comment by MalakymR** [comment]
+1 fo sqlite at least, goes with the u in ulogger.

**Comment by jensMF** [comment]
+1 for sqlite too, would be awesome

**Comment by pierre-guillot** [comment]
+1 for sqlite, use an old rapsberry pi 1 as server and don't want to installer a mysqlserver on it :)

**Comment by bfabiszewski** [comment]
I migrated database support to PDO, so both PostgreSQL and SQLite will be supported in the next release (now available in git beta)
