### ISSUE TITLE
OpenCycleMap: Api Key required for all requests

### ISSUE THREAD

**Issue by shoeper** [bfabiszewski/ulogger-server#26]
Looks like it can be obtained at http://www.thunderforest.com/docs/apikeys/

And afaik there is no option so far to configure one in ulogger.

**Comment by shoeper** [comment]
Manual solution is to register and add the api key at js/api_openlayers.js
Search for thunderforest.com.

**Comment by bfabiszewski** [comment]
I'll close this issue. I'll address it in #27, which is related.

**Comment by shoeper** [comment]
Thanks. All in all a good application in combination with the app. Was able to travel my summer trip without draining my battery and now can easily have a look at it from my PC.
