### ISSUE TITLE
MapQuestOSM & osmapa.pl & UMP: name not resolved

### ISSUE THREAD

**Issue by shoeper** [bfabiszewski/ulogger-server#27]
Looks like they're either down or addresses changed.

I'm not much into it but if these layers all work the same way it could be a good idea to have a list of layers in the config with name, api endpoint and enabled/disabled instead of options for some layers. This list could also allow settings an api key if required.

**Comment by bfabiszewski** [comment]
> I'm not much into it but if these layers all work the same way it could be a good idea to have a list of layers in the config

This is a good idea. I'll have a look at it.

**Comment by shoeper** [comment]
That was pretty fast, thanks.

Giving it a try soon. In combination with the app it worked great during my holiday trip. Especially being able to configure the capture intervall was very helpful to not drain my battery too fast.
