### ISSUE TITLE
Database connection error

### ISSUE THREAD

**Issue by stemy2** [bfabiszewski/ulogger-server#28]
Hello,

I can't access to the database. When i try to load index.php, i have the following message:

`Database connection error (Access denied for user 'webapp1'@'localhost' (using password: NO))`

«Webapp1» is the username i used to transfer the files to my server through SFTP. Did i something wrong ?

Thanks.

**Comment by bfabiszewski** [comment]
There seems to be a problem with your configuration. Did you set proper database credentials in config file? These are probably different than sftp user and password.

**Comment by stemy2** [comment]
Yes, they are. But i'm a newbie at mysql, so i certainly did other mistakes. Is it possible to have more detailed instructions for the database creation ?

Thanks.

**Comment by bfabiszewski** [comment]
This is a broad subject. All depends on your system, tools you use etc.
Generally you need to set up a database and create user that has the privilege to create tables in that database. Then you should enable and start setup script as described in Readme.

The error message you get may suggest your password is empty.

**Comment by stemy2** [comment]
Actually, i only had to use the login and password idicated on the txt file wich is at the root folder.
