### ISSUE TITLE
1) Save points when no connection 2)"Android Wear" version of the app?

### ISSUE THREAD

**Issue by kalakrumanov** [bfabiszewski/ulogger-server#29]
I use it in my phone, and works like a charm, I have only 2 comments about it:

1) I usually run at mountains, and lots of times there are some places with no internet connection (similar to airplane mode) so obviously no gps points are transferred. The good news is that the app automatically sends gps points again where there is internet connection. The bad news is that "all that time" with no internet connection, it simply draws a line (the gps points where not saved and sent later when there is internet connection again). 

So, it would be great if the app could save those gps points I have during the "no internet connection time", and when it detects that there is connection, send all of those gps points that where saved. 

2) My family is now engaged with the app, because almost all of us run or bike. But I think it would be great if there is a possibility to make an "Android Wear" of the app, a really simple one, so that way I am sure more people will use it and love it :) 

Only 1) is an issue, 2) could be a pull request.

**Comment by bfabiszewski** [comment]
Hi, thanks for feedback!

1. 
This behaviour is strange. Normally, with no internet connection, it still logs positions and sends it to the server when internet connection is available again. This is how I usually use it. 
There is probably some issue with the app not getting position when internet connection drops. Check µlogger settings. Maybe the accuracy is below the threshold, and the position is discarded? Is GPS provider on? What device is affected? Did you try other devices?
Also check whether other applications can get correct position at the same time that µlogger fails.

2.
Android Wear would be interesting thing. I may have a look at it when I find some time (not top priority though). If you want to contribute such feature, you are most welcome.

**Comment by kalakrumanov** [comment]
Thanks for your answer @bfabiszewski ! I will try it again soon, and will post the results os 1)

Do you have a FAQ for the APP? Because, for example, for explaining what exactly means "minimum accuracy", or if you have multiple conditions for the signal, "Does the signal is sent when 1 of them is satisfied, or when ALL of them are satisfied?" 

Thanks in advanced!

**Comment by kalakrumanov** [comment]
As I don't where else to ask about it @bfabiszewski  : Why do you think is happening that sometimes there is no GPS point on the map? Does it has to do with my configuration of the app? Everything else is working perfectly :) 

![screen shot 2017-08-08 at 3 37 17 pm](https://user-images.githubusercontent.com/16352883/29074443-99f9a9ea-7c4f-11e7-8a05-81a51892965c.png)

This was a couple of hours ago. The conf I have is: (if you need more info, just ask for it)

Min. Accuracy: 25m
Min. Distance: 50m
Min. Time: 30sec
Loc Provider: Network & GPS

Cheers!

**Comment by bfabiszewski** [comment]
Your config parameters mean that new location will be logged if you moved at least 50 meters and it took at least 30 seconds. It is a way to limit too frequent updates (and save battery).

Another think is accuracy. If location accuracy, as reported by GPS, is greater than 25 meters (meaning less accurate) it will be discarded. The position will not be logged. It is a way to get rid of low quality data, but it depends on your device and the terrain.

I believe you should increase accuracy tolerance and try again. It is possible that location updates are discarded when the quality of GPS signal drops (for example in forest).

You can click on each track point in µlogger web viewer and check the accuracy of your positions. It will give you an idea how to set the threshold.

**Comment by kalakrumanov** [comment]
I really appreciate your response. This helped me a lot configuring the app.

As I said, a FAQ with the "typical questions" would help a lot the users of ulogger, for sure.

Thanks Bartek!
