### ISSUE TITLE
Not an issue, but a question: How do you create new users? 

### ISSUE THREAD

**Issue by kalakrumanov** [bfabiszewski/ulogger-server#33]
Sorry if this is a stupid question, but I have been trying it for more than an hour, with no results... 

How do you create new users?  (As I said, if you make a FAQ it would be create @bfabiszewski :) )

Thanks in advanced. Kalak

**Comment by kalakrumanov** [comment]
Ok, I finally managed to do it. 

In the config.php must set up "You may also want to set your new user as an admin in config file."

Cheers!!

**Comment by bfabiszewski** [comment]
Great that it works. I'll be able to compose a FAQ from your issues soon :)
If you find time you could also contribute a FAQ section of the README yourself.
