### ISSUE TITLE
is it possible to allow other client apps to use the ulogger server?

### ISSUE THREAD

**Issue by fm444fm** [bfabiszewski/ulogger-server#36]
I am wondering how it could be possible to extend the usage of ulogger-server to other client apps, not just with your ulogger-client.

From what I understood, the android app accesses /client/index.php, authenticates through /auth.php, sends an "addtrack" action and gets a trackid, then later on uses the same trackid on each call to the action "addpos" for each location which needs to be logged.

I tried to modify the "addpos" action so that it can be optionally used with a trackname argument, which then queries (via track->getAll) to see if a track with that name exists and - if it does - retrieves the appropriate trackid, or - in case it doesn't - it creates a new track like the "addtrack" action.

This more or less works ok and should be enough to allow other loggers to use the server with a single call to the url (a single call for each position logging event).

But I am not sure how your server deals with authentication and how to do it with a single url call.
Would it be possible to authenticate the user directly via httpd, for example by making a call to this kind of URL "https://USERNAME:PASSWORD@servername.domain/ulogger/client/index.php?action=addpos&lat=LAT&lon=LON&time=TIMESTAMP&trackname=TRACKNAME"?

Thank you

**Comment by bfabiszewski** [comment]
Authentication is based on php session. Id is stored in a cookie. 
Client must support cookies.

To make it work with your example URL you would have to modify authentication mechanism.

**Comment by Egauss** [comment]
So if I want use arduino with GPS I need tweak code with password hash?

**Comment by bfabiszewski** [comment]
You could adjust arduino client to support µlogger API.

I wanted to make arduino client myself, but didn't have time yet. Still have to buy gps/gsm shield.

**Comment by Egauss** [comment]
At this moment I am using arduino with SIM808 and it's sends string to http, just need pass login. 

Got some locations on Google map api, but my server code have lot of bugs and non of security

**Comment by mendhak** [comment]
> You could adjust arduino client to support µlogger API.

Hi @bfabiszewski by this API do you mean getting a client to specifically implement cookie auth or is there a token type mechanism that can be used?  Or would it be possible to have a token based mechanism or a basic-auth mechanism so that a generic client can simply issue a few regular GET requests against a ulogger server? 

> Also note that passing password in URL is not safe. Even using SSL the URL will not be encrypted and will be visible on the way to server and in server logs.

Just wanted to point out in case this is the reason for not doing - it is commonly thought however - with https the querystring, headers and body are [all encrypted](https://stackoverflow.com/questions/499591/are-https-urls-encrypted).  Only the domain name is available via SNI. You can see it yourself via Wireshark or Fiddler

**Comment by bfabiszewski** [comment]
Hi @mendhak 

Currently authentication is only cookie based. I created this project mainly for my own needs and never thought it would require extending to other clients. But now, as there is demand, I think I could add a very simple backwards compatible pseudotoken authentication method:
- after successful authentication, apart from cookie, server would return session token in json response.
- on each client request server would check for the token being present in request and restore session even if cookie was not used.
Would it be ok?

You are right about query parameters being encrypted over SSL, my mistake. Still I don't like the idea of passing credentials in url and also don't see any benefit of using HTTP basic authentication.

**Comment by bfabiszewski** [comment]
@mendhak 
It could be as simple as this:
https://github.com/bfabiszewski/ulogger-server/tree/token-authentication

Would it work for you?

**Comment by bfabiszewski** [comment]
Client authenticates and receives the token:
```
$ curl -d "action=auth&user=USERNAME&pass=PASSWORD" -X POST  http://ulogger.dev/client/

{"error":false,"token":"91m5s1mbpg106m5ghub7bs22q1"}
```
Subsequent requests must provide token using "token" parameter:
```
$ curl -d "token=91m5s1mbpg106m5ghub7bs22q1&action=ACTION" -X POST http://ulogger.dev/client/
```

**Comment by mendhak** [comment]
Ah sorry I didn't give the full context of my question!  @fm444fm  posted on my  [Android app](https://github.com/mendhak/gpslogger/issues/590) - where I have a generic Custom URL logging feature.  He's trying to get it to work with ulogger.   Only issue on my side is the Custom URL logger is stateless - so in this case it would work well with the second part of your latest post - 

    curl -d "token=91m5s1mbpg106m5ghub7bs22q1&action=ACTION" -X POST http://ulogger.dev/client/

But doing the first call to authenticate and get a token would make it bespoke.

So around this I have a question - the token that is returned, is that a non-expiring token? 

If it is a non-expiring token, then I am thinking -  I could ask the user to manually run a `curl` command, get the token from the response, then plug the token into the Custom URL logger.

**Comment by mendhak** [comment]
>  I created this project mainly for my own needs and never thought it would require extending to other clients. 

I think you've created something great and thanks for sharing it with the world!  Of course with the sharing comes a legion of never ending requests :grin:

**Comment by bfabiszewski** [comment]
> So around this I have a question - the token that is returned, is that a non-expiring token?

Unfortunately it will expire. 
For creating stateless token I would need more time. Now I am not even sure if I want it. 

> I think you've created something great and thanks for sharing it with the world!
And who says that! Look at your own app :)
