### ISSUE TITLE
Live demo website is down

### ISSUE THREAD

**Issue by anmol26s** [bfabiszewski/ulogger-server#37]
Hi
The demo website http://ulogger.fabiszewski.net/ shows **Not Found** error. Is it no longer maintained ?

**Comment by bfabiszewski** [comment]
Thanks for the info!
It was hosted on OpenShift 2 servers that were shut down. 
I migrated to OpenShift 3. Should be up now.

**Comment by anmol26s** [comment]
Its working now. 
Thanks :+1:
