### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by Hippyjake** [bfabiszewski/ulogger-server#4]
I think a Docker image would make a great option to install this.

**Comment by bfabiszewski** [comment]
Docker could be an option, but I've never used it, so maybe some day. Also this project has minimal dependencies. Should be pretty straightforward to install it. I also added a simple setup script recently.

**Comment by ranomier** [comment]
Like everything is better with bluetooth, i think, everything inside docker is better, too. :)

Who got the reference?

**Comment by bfabiszewski** [comment]
I cooked basic docker image.

`docker run --name ulogger -p 8080:80 -d bfabiszewski/ulogger`
