### ISSUE TITLE
could not create new user 

### ISSUE THREAD

**Issue by lrmodesgh** [bfabiszewski/ulogger-server#40]
i have successfully instantiated ulogger-server.
i have created an admin user as instructed.

But when i try to create a new user in "administration" in the right panel, the following error occurs : 
 "Something went wrong. Server error"

![screenshot_20171106_160629](https://user-images.githubusercontent.com/6794375/32437289-b8fdf686-c2de-11e7-9e73-5262b5051dd0.png)

**Comment by bfabiszewski** [comment]
Hard to tell. Maybe there is something wrong with database setup. Are you able to log positions to database? Or import gpx track?
Also check the webserver logs for warnings/errors.

**Comment by lrmodesgh** [comment]
nope, i could not log positions from android ulogger, as well as i am unable to import gpx track.
while trying to import a gpx track - "u need username and password to access this page" error occurs.
Then i have to relogin again to see the ulogger server page.

**Comment by myuseraccount** [comment]
I have these same symptoms. Just installed on Nginx, MariaDB and PHP 5.4. When I try to connect from the Android app to the one user created during setup, it gives a 401 not authorized.

**Comment by myuseraccount** [comment]
Also, I manually added a second user entry to the database, but when I choose "edit user" it opens this dialog, and I can't select the user to edit.
![image](https://user-images.githubusercontent.com/39630717/40558553-8287623c-6008-11e8-8f4e-0a210281e2ed.png)

**Comment by bfabiszewski** [comment]
@myuseraccount 
Generally you should choose user first, from `user` form select field. The `edit` option works for user selected in this field.

Now I see there is a bug. The edit form should not open when no user is selected. I'll have to fix it.

**Comment by myuseraccount** [comment]
Thanks, I did select a user first after that. It gives the same "server error" message as trying to create a user, that @lrmodesgh posted. These entries in my Nginx log might be a clue, I'm not sure what is failing to write. (I replaced my client and server addresses for privacy.) 

```
2018/05/25 20:41:20 [error] 516#0: *24187 FastCGI sent in stderr: "PHP message: PHP Warning:  session_start(): open(/var/lib/php/session/sess_d0ue97v8u363mv16k6bcsv7n10, O_RDWR) failed: Permission denied (13) in /usr/share/nginx/html/ulogger/helpers/auth.php on line 79" while reading response header from upstream, client: {MYDESKTOP}.199, server: pr.ohut.ch, request: "GET /ulogger/utils/logout.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/fastcgi.sock:", host: "{MYSERVER}", referrer: "https://{MYSERVER}/ulogger/"
2018/05/25 20:41:20 [error] 516#0: *24187 FastCGI sent in stderr: "PHP message: PHP Warning:  session_start(): open(/var/lib/php/session/sess_3ugmo93ctut8mjkr1btnjm1ae5, O_RDWR) failed: Permission denied (13) in /usr/share/nginx/html/ulogger/helpers/auth.php on line 79
PHP message: PHP Warning:  Unknown: open(/var/lib/php/session/sess_3ugmo93ctut8mjkr1btnjm1ae5, O_RDWR) failed: Permission denied (13) in Unknown on line 0
PHP message: PHP Warning:  Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/lib/php/session) in Unknown on line 0" while reading response header from upstream, client: {MYDESKTOP}.199, server: pr.ohut.ch, request: "GET /ulogger/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/fastcgi.sock:", host: "{MYSERVER}", referrer: "https://{MYSERVER}/ulogger/"
```

**Comment by bfabiszewski** [comment]
@myuseraccount 
Glad to here you solved it.
