### ISSUE TITLE
Export GPS Log as a CSV

### ISSUE THREAD

**Issue by mattfleaydaly** [bfabiszewski/ulogger-server#46]
Is there a way that this can be achieved easily?
Thanks!

**Comment by bfabiszewski** [comment]
Export to GPX and convert it with some third-party tool?
For example: https://mygeodata.cloud/converter/gpx-to-csv
I've never tried it though.

**Comment by mattfleaydaly** [comment]
Whilst that is a good option, If there was one built in it would be alot easier in my opinion.
Hence why I ask the question? :)
