### ISSUE TITLE
How to add users ?

### ISSUE THREAD

**Issue by stemy2** [bfabiszewski/ulogger-server#52]
Hello,

I don't understand how to add users, there is no «add user» on the right toolbar, and i'm the admin. Could someone explain me how to do it ?

Thanks

**Comment by markwaters** [comment]
You should have an ordered list of Add User , Edit User and Edit Track at the bottom right of the toolbar.
Have you set your user to $admin_user in config.php ?

**Comment by stemy2** [comment]
It works.

Thanks.
