### ISSUE TITLE
End of input at character 0 of

### ISSUE THREAD

**Issue by nahkampf** [bfabiszewski/ulogger-server#54]
I've set up a ulogger server (php 7.0.22) and run the app, but the app never synchronizes ("x positions behind"), with the error message "End of input at character 0 of" [sic]. Can't see anything in my php error log. Ideas?

**Comment by bfabiszewski** [comment]
There must be a problem with communication between app and server. Client receives unexpected response and can't parse it.

If your host url in `http://www.example.com`, the client connects to `http://www.example.com/client/index.php`. You may try to connect to this url from your browser and see if there is any response.
