### ISSUE TITLE
Error: Sorry, can't load openlayers(3) API

### ISSUE THREAD

**Issue by jensMF** [bfabiszewski/ulogger-server#55]
Whenever I choose openlayers I get this message : Sorry, can't load openlayers API or Sorry, can't load openlayers3 API. What can I do?

**Comment by jensMF** [comment]
Ok I found the problem. The URLs have to end with /${x}/${y}/${z}.png

**Comment by bfabiszewski** [comment]
I don't understand this issue, but it seems you already solved it, so closing now.

**Comment by stemy2** [comment]
I have the problem too, i didn't understand the solution either. I have the message as error when i'm opening the app, and a brown background instead of the expected OSM map.

**Comment by bfabiszewski** [comment]
It means that website can't connect to OSM server.
Try to restore default settings for `$ol_layers` variable in [config](https://github.com/bfabiszewski/ulogger-server/blob/b957893300cd0b3ce260b8b237798ea1a3cba52e/config.default.php#L29) file.
Clear browser cache/cookies for µlogger page, reload and check if it helps.

**Comment by stemy2** [comment]
OK, i deleted the «3» in «Openlayers 3», and now, it works.

**Comment by bfabiszewski** [comment]
I see, you were using config file from an old version
