### ISSUE TITLE
Removing track. Causes realtime tracking to not able to upload new data to the DB

### ISSUE THREAD

**Issue by JoneKone** [bfabiszewski/ulogger-server#57]
Remove track from webinterface creates a situation where ongoing (realtime) gps log data cannot be uploaded anymore from phone.

As a super user, when I remove my friends ongoing track in web interface the phone stops uploading track info in real time, with an error message.

0.5 Beta web(server) 1.8 android program.

**Comment by bfabiszewski** [comment]
This is very simple software and there is no track write-locking for single client. 
So if you edit your track from multiple clients at the same time (from different web sessions or Android clients) if will fail.
