### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by DieterVanWerkum** [bfabiszewski/ulogger-server#59]
Hi bfabiszewski,

Nice work and works like a charm over (not secure) http. But . . . 

Ever since I implemented SSL on my hosted webserver my Android client errors 'handshake aborted'. While more recent Android phones have no problems on my cyanogenmod custom rom (details below):
- I can login  to the web-interface (with Firefox on my phone) and navigate the map. But I can't operate the 'last position and 'auto update' checkboxes in the sidebar; 
- The ulogger app throws 
"javax.net.ssl SSL Protocol Exception . . . handshake aborted . . . usually error 14077410: SSL routines SSL 23_GET_Server_Hello ssl-v3". 

Where's the logic in this combination?My custom Android rom is  [GT-I9001][ROM][ION][4.4.4][KTU84Q] CyanogenMod 11.0 by ADC-Team - Release 17 [EOL] and SSL implementation is via a http 301 redirect in htacces).

Best regards,
Dieter

**Comment by rahra** [comment]
I run ulogger within Apache/PHP with TLS without any problem.
It may be a configuration issue of your client or server.
ssl-v3 is deprecated.

**Comment by bfabiszewski** [comment]
It may be difficult to trace down.
Try running SSL tests against your server: https://www.ssllabs.com/ssltest/
Some old SSL setups may not be supported by Android client.

**Comment by DieterVanWerkum** [comment]
Thanks guys,

@bartek: The test shows (that my Android 4 is the oldest tested configuration;-) but that the overal test  result (of my third party SSL provider, COMODO RSA Domain Validation Secure Server CA) is "A".

Since other users report no errors I'll consider upgrading my faithfull old sgs+ to Lollipop custom rom that I discovered the other day.

Great initiative Bartek, thanks again,
Dieter

**Comment by bfabiszewski** [comment]
@DieterVanWerkum 
I am logging my tracks using very old device running Android 2.3.6. It works with SSL enabled webserver. So your problem is not too old version, but probably some particular SSL configuration on server that is not supported. You might try to disable SSLv3 on your server, if possible.

**Comment by DieterVanWerkum** [comment]
That's great news Bartek! I see I jumped to conclusions too fast because I have too little knowledge of SSL. I'll look into the possibility of disabling SSLv3.

I wouldn't call my phone old, rather 'faithfull' ;-)

Best wishes,
Dieter
