### ISSUE TITLE
De-google-ify the server files

### ISSUE THREAD

**Issue by stemy2** [bfabiszewski/ulogger-server#61]
Hello,

I try to remove any content that makes requests to google from my server, but it's really difficult. Could you write an «how to» ?

Thanks.

**Comment by bfabiszewski** [comment]
First of all your server doesn't make any requests to google. Your browser does.

There are three components that make use of google services.
1. Google maps API. It is used only if you choose this API from dropdown list. If you want to make sure you never use it you would have to remove it from the dropdown select field leaving only Openlayers API option.
2. I also use webfonts from Google fonts repo. You could delete [this line](https://github.com/bfabiszewski/ulogger-server/blob/ed05a9f96c6fc7b5c19c5d0e83924ae2abef7572/meta.php#L11). Or replace it with locally uploaded fonts.
3. I use Google charts to draw altitudes. You may try to comment out the lines referring to Google APIs [starting here](https://github.com/bfabiszewski/ulogger-server/blob/ed05a9f96c6fc7b5c19c5d0e83924ae2abef7572/index.php#L92). And remove 'show altitudes' link.

These are quick notes, so you will have to try it and improvise if something breaks.

**Comment by stemy2** [comment]
The problem is back. I deleted the line from the meta.php, but it didn't chaged anything, it still load the google fonts.

**Comment by bfabiszewski** [comment]
I am working on a new version where this dependency is dropped.
Until I release it you are on your own, sorry.
