### ISSUE TITLE
ulogger server defaulting to "http" in BASE_URL

### ISSUE THREAD

**Issue by axb21** [bfabiszewski/ulogger-server#62]
At least, I could not figure out how to tell the server to use https. This manifested at login time, when the login process attempted to hit "http://MYSERVER..." instead of "https://MYSERVER...", and login failed silently. The problem went away when I hardcoded my https URL in auth.php. If this is a configuration option, the place to perform that configuration was not obvious to me.

**Comment by bfabiszewski** [comment]
The protocol prefix is determined [automatically from server HTTPS variable](https://github.com/bfabiszewski/ulogger-server/blob/ed05a9f96c6fc7b5c19c5d0e83924ae2abef7572/helpers/utils.php#L117).

Generally you don't have to do anything if you open main page with `https:// `scheme.
There may be something unexpected in your web server configuration that redirects request to nonsecure URL. What is you web server, PHP setup? Try to print out the contents of `$_SERVER["HTTPS"]` variable when connecting with `https` prefix.
