### ISSUE TITLE
Are there plans to expose an API?

### ISSUE THREAD

**Issue by virtadpt** [bfabiszewski/ulogger-server#63]
First, thank you very much for ulogger.  I'm having a lot of fun with it!

Do you have any plans to expose a REST API in the ulogger-server?  I'd like to hook some of my constructs into my instance.

**Comment by bfabiszewski** [comment]
As you can see in the issues tracker the list of feature requests is growing. Adding REST API will not have a high priority with the limited time I have I am afraid.
