### ISSUE TITLE
Only track latest location

### ISSUE THREAD

**Issue by Cyllos42** [bfabiszewski/ulogger-server#65]
Hello

I'm looking for an anti theft tracking service. I set up your client and server and I'm very happy with the result.
I was wondering if it would be possible to only track the latest location of my phone, instead of creating a location history. If so, could you show me how? Or at least where I should start.

Thanks

**Comment by Cyllos42** [comment]
I changed trackId in the getPosition.php, which does kinda work, only the other locations are still saved

**Comment by bfabiszewski** [comment]
On the ulogger-server you may display only latest position (by selecting related checkbox).

If you want to save space in database you may write a simple script – just a mysql query that will delete old positions (e.g older that 24 hours). Then you might run such script as a cron job (e.g every hour).
