### ISSUE TITLE
sharing your tracks

### ISSUE THREAD

**Issue by radlerandi** [bfabiszewski/ulogger-server#66]
hi, i finally managed to install ulogger on my synology nas and it's working fine.
But my use case was to share the (a) url with other people (and if necessary guest login data) so they are able to see my location/track when i'm on a multiple day bike trip.
I created a new user, but this user is not able to see the track of my user. So i guess i have to share the main user, but then they are able to change and delete everything, so this is quite pointless.

any ideas?

**Comment by bfabiszewski** [comment]
[public_tracks](https://github.com/bfabiszewski/ulogger-server/blob/master/config.default.php#L58) config option should do the trick

**Comment by radlerandi** [comment]
yes! this is what i wanted. And i also tested "require_authentication=0", but i think with a guest user and a 4 letter password it should be simple enough for my viewers.
I should have taken a closer look to the config file, but struggled with the installation on my synology .. so ..... 
thanks! :)
