### ISSUE TITLE
PHP7.2

### ISSUE THREAD

**Issue by DieterVanWerkum** [bfabiszewski/ulogger-server#75]
Hi Bartek,

My host forced PHP 7.2 on me for all the good reasons. The app is still working fine, but logout now shows some auth.php warnings (see below).

Do you have plans to update?

Best regards,
Dieter

logout.php throws three warnings:
Warning: session_name(): Cannot change session name when session is active in /customers/6/9/f/aotp.nl/httpd.www/ulogger-server/helpers/auth.php on line 91
Warning: Cookie names must not be empty in /customers/6/9/f/aotp.nl/httpd.www/ulogger-server/helpers/auth.php on line 93 
Warning: Cannot modify header information - headers already sent by (output started at /customers/6/9/f/aotp.nl/httpd.www/ulogger-server/helpers/auth.php:91) in /customers/6/9/f/aotp.nl/httpd.www/ulogger-server/helpers/auth.php on line 181

**Comment by bfabiszewski** [comment]
Thanks for detailed report!
I see the problem, I'll fix it soon.
