### ISSUE TITLE
alternative ulogger-server in ruby

### ISSUE THREAD

**Issue by fauno** [bfabiszewski/ulogger-server#76]
hi! at partido interdimensional pirata we really liked µlogger the app, but found out µlogger-server didn't fit our needs, and php is not a language we're proficient on, so we made a new µlogger-server based on sinatra and jekyll (both ruby frameworks).  this server collects points from several devices and shows them together in a single map if they share the same group name.  more or less like etherpad works.

thanks for µlogger!

* [press release + instructions](https://partidopirata.com.ar/2018/11/30/una-app-para-recuperar-la-soberania-colectiva-sobre-nuestras-cuerpas/)
* [frontend](https://0xacab.org/partido-interdimensional-pirata/jekyll-ulogger)
* [backend](https://0xacab.org/partido-interdimensional-pirata/ulogger-sinatra)

**Comment by bfabiszewski** [comment]
Thanks for letting me know and for choosing µlogger!
Nice idea.
It works :0 https://ulogger.partidopirata.com.ar/?grupo=test
Good luck and greetings from Poland!
