### ISSUE TITLE
Map-UI does not show any positions

### ISSUE THREAD

**Issue by rapht0r** [bfabiszewski/ulogger-server#81]
Just installed everything, Syncing works fine.
The locations show up in the database but not on the map.
Javascript is enabled. Am I missing something very obvious?
I'm also logged in as the user that uploads the data.
Edit: The demo map works just fine.
Might it have something to do with the fact that I'm running in the local network only?

**Comment by bfabiszewski** [comment]
Hard to tell. Local network should matter.
Are there any errors in javascript console or in web server logs?

**Comment by rpauwels** [comment]
FYI, I had the same problem and here the cause was that php-xml was not installed.

**Comment by bfabiszewski** [comment]
@rpauwels 
Thanks for sharing your experience
