### ISSUE TITLE
Docker image with Let's Encrypt SSL cert?

### ISSUE THREAD

**Issue by ei8fdb** [bfabiszewski/ulogger-server#82]
(This is a question of support rather than an issue)

Is it possible to give some assistance on how to get ulogger-server secured with Let's Encrypt cert?

I'm familiar with day-to-day Docker admin tasks, but not with implementing Let's Encrypt SSL certs with Docker images.

Alternatively, could someone give me a starter on how to make a docker image with Let's Encrypt Certbot rolled in?

**Comment by bfabiszewski** [comment]
Never used certbot in docker. Maybe [this article](https://medium.com/@pentacent/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71) will help you.
