### ISSUE TITLE
Cannot login with app

### ISSUE THREAD

**Issue by moose999** [bfabiszewski/ulogger-server#86]
Hi,

I always get error 401 in the app. I can log into the site on the web browser on the mobile device with the same username/password combo, so its not incorrect credentials. I can see log entries like:

"POST /client/index.php HTTP/1.0" 401 454 "-" "ulogger/2.5; Dalvik/2.1.0 (Linux; U; Android 9; Pixel XL Build/PQ2A.190405.003)"

Additionally, when I try and create a new user, I get:
"Something went wrong
Server error".

I am on Ubuntu 18.04.2 with PHP 7.2.15

Thanks,
Justin

**Comment by moose999** [comment]
After further testing, I presume this is not PHP7 compatible. Is there any chance this will be resolved?

**Comment by bfabiszewski** [comment]
Sorry for not responding earlier.
Which is your µlogger version? Is it latest git version or some other released version?
Difficult to say what your problem might be. Definitely not PHP version as I am testing it against 7.2 (unless you are using some ancient app version).
I assume some problem with database. Maybe µlogger setup script has some issues, as it was not well tested after latests changes.
Which database engine are you using?

**Comment by moose999** [comment]
Hi,

I am using the latest 'release' - Version 0.5. I have tried this version on a different server, and it was fine, so I think the script is good, Maybe something else with my environment. 

I am using MySQL.

Many thanks!

**Comment by bfabiszewski** [comment]
Maybe you have some problem with PHP session handling? 
Please make sure that PHP has properly configured path to save session data and that it has permission to write to this location.

**Comment by moose999** [comment]
Hi,

I think its OK - I can see sess_XXXXXXXXXX files being created in my session save path. Please see my PHP info:

http://tracker.bongoit.co.uk/info.php

Many thanks for your help!

Justin

**Comment by bfabiszewski** [comment]
I think the problem is `session.auto_start = On`. 
Please check whether disabling this option helps.

**Comment by moose999** [comment]
It certainly is, many thanks for all your help with my server, and for all your work on this script!

**Comment by bfabiszewski** [comment]
Good to know. I should add check for the setting in setup script.
Thanks for testing!
