### ISSUE TITLE
Set Admin Password via Environment

### ISSUE THREAD

**Issue by jojomi** [bfabiszewski/ulogger-server#88]
I would like to be able to configure the admin user's password via an environment variable, so it can be done when running inside docker.

What do you think?

**Comment by bfabiszewski** [comment]
I am only using docker for tests. I have no experience in running production server in docker container, so correct me if I am wrong.
Couldn't you just run [setup script](https://github.com/bfabiszewski/ulogger-server/blob/master/scripts/setup.php) on first run to make database setup and set password from interactive script?
I just pushed a commit I had made some time ago for the purpose of testing which allows to enable setup script with environment variable.
