### ISSUE TITLE
database 

### ISSUE THREAD

**Issue by balasmeh** [bfabiszewski/ulogger-server#89]
sir where is the database file?

**Comment by bfabiszewski** [comment]
What do you mean?
Database location depends on your server's system and db engine.

**Comment by balasmeh** [comment]
I mean the database file of this project, I can't found it

**Comment by bfabiszewski** [comment]
If you mean database structure dump, you may find files for different engines in [scripts](https://github.com/bfabiszewski/ulogger-server/tree/master/scripts) directory.
However you should not need it. Setup script will create database structure for you.

**Comment by balasmeh** [comment]
ya i got it, thank you sir, and another think , how about geofence , is there any code that user able to create geofence and store in database based on this project?

**Comment by bfabiszewski** [comment]
No, sorry. There is no geofencing support in this application. Just logging position and tracks.

**Comment by balasmeh** [comment]
ok sir, thank you again
