### ISSUE TITLE
See all users on map

### ISSUE THREAD

**Issue by Yogosh** [bfabiszewski/ulogger-server#9]
I was wondering if you could add an option to see last position of all users.

**Comment by Lebewesen** [comment]
To leave ulogger always running it would be good to commit the position not as part as a track. Maybe a last postion entry in the database wich is always overritten or a continius logging without a track.

I can help on the server side but not on the app.

**Comment by bfabiszewski** [comment]
@Lebewesen 
Without overwriting last position you will retain access to location history.

I am currently busy, but I think this feature is worth implementing. I'll get back to it.

**Comment by Lebewesen** [comment]
@bfabiszewski
It's a cool feature. My idea (2) was that continius tracking isn't bound to a track. Only if i "switch on" the track mode it will be recorded as a track. I have then a complete history of my locations and some points wich are marked as Tracks. At the moment I only use ulgger as a track recorder and it is turned of normaly. A continius tracking that isn't bound to a track would be cool. I don't know if this is another feature?

There is no time pressure - this program is a hobby :-) I also make my fixes when I have time.

**Comment by MalakymR** [comment]
You could allow tracking (keeping history) without "tracks", and have tracks as an optional setting for the user to specify a specific part of the route.

This would need date/time filtering on the track filtering instead (on the web ui side).

**Comment by clawoflight** [comment]
This would actually be my primary use case.
Consider this a +1 and thread subscription :)

**Comment by jensMF** [comment]
I would love to be able to see live tracks of all users at the same time and to be able to view and compare tracks of different users. My use cases are coordination of teams for the live part, and quality of training, when one team tracks another for the comparison part.
Thanks for the great work so far.
