### ISSUE TITLE
Can't set up SQLite database without username specified

### ISSUE THREAD

**Issue by Forkest** [bfabiszewski/ulogger-server#90]
Because `$dbDriver` is null at [this stage](https://github.com/bfabiszewski/ulogger-server/blob/7acc3df67d99d256c6248eb88530ce8b09dd61c4/scripts/setup.php#L124).

**Comment by bfabiszewski** [comment]
Thanks for catching this!
As a temporary workaround before I fix it, you may set a dummy user name.

**Comment by Forkest** [comment]
I've already done this, it works. Thank you for adding SQLite support.
