### ISSUE TITLE
TypeError: usersSelect is undefined when checking "latest position" or "autoreload"

### ISSUE THREAD

**Issue by Forkest** [bfabiszewski/ulogger-server#91]
In Firefox. [main.js:515](https://github.com/bfabiszewski/ulogger-server/blob/69cf9ade47a66fe5d6282ea643bf9c1262bbbbfc/js/main.js#L515):3 and main.js:520:1

I have just one user and he is not an admin, if that matters.

**Comment by bfabiszewski** [comment]
I am working on a major javascript refactoring.
I think I will fix this case in this new version.

**Comment by bfabiszewski** [comment]
Duplicate of #100
